/*
 * Copyright (c) 2021 Acme CPU
 *
 *  Created on: 01-Mar-2022
 *      Author: Rohan Dey (rohan@acmecpu.com)
 */

#ifndef SRC_APP_APP_DISPLAY_C20X_SCREENS_C20X_SCREEN_CONFIG_H_
#define SRC_APP_APP_DISPLAY_C20X_SCREENS_C20X_SCREEN_CONFIG_H_


#define APP_DISPLAY_WIDTH_PX				CONFIG_APP_DISPLAY_WIDTH_PX
#define APP_DISPLAY_HEIGHT_PX				CONFIG_APP_DISPLAY_HEIGHT_PX
#define APP_DISPLAY_STATUSBAR_HEIGHT_PX		CONFIG_APP_DISPLAY_STATUSBAR_HEIGHT_PX

/* Style properties */
#define C20X_SCREEN_STYLE_TEXT_LETTER_SPACE_SQUEEZED		(-1)
#define C20X_SCREEN_STYLE_TEXT_LETTER_SPACE_SQUEEZED_HIGH	(-2)

/*
 * 	 ------------------------------
 * 	|			status bar		   |
 * 	|------------------------------|
 * 	|							   |
 * 	|							   |
 * 	|			main area		   |
 * 	|							   |
 * 	|							   |
 * 	 ------------------------------
 */
//#define C20X_SCREEN_SBAR_HEIGHT_PERCENT		(18)
//#define C20X_SCREEN_SBAR_HEIGHT_PX			10 //(APP_DISPLAY_STATUSBAR_HEIGHT_PX) //((APP_DISPLAY_HEIGHT_PX * C20X_SCREEN_SBAR_HEIGHT_PERCENT) / 100)

#define C20X_SCREEN_NUM_LINES_MAX			(5)
#define C20X_SCREEN_SBAR_HEIGHT_PX			(APP_DISPLAY_HEIGHT_PX / C20X_SCREEN_NUM_LINES_MAX)

#define C20X_SCREEN_MAIN_X_START_PX			(0)
#define C20X_SCREEN_MAIN_Y_START_PX			(C20X_SCREEN_SBAR_HEIGHT_PX)

/* dashboard / home screen */
#define C20X_SCREEN_DASH_WIDTH_PX			APP_DISPLAY_WIDTH_PX
#define C20X_SCREEN_DASH_HEIGHT_PX			(APP_DISPLAY_HEIGHT_PX - C20X_SCREEN_SBAR_HEIGHT_PX)
#define C20x_SCREEN_DASH_PADDING			(3)
#define C20X_SCREEN_DASH_NUM_LABELS_TO_DISP	(4)
#define C20X_SCREEN_DASH_NUM_ICONS_TO_DISP	(2)
#if (CONFIG_C20X_SCREENS_OLED)
#define C20x_SCREEN_DASH_LABEL_WIDTH_MAX	(C20X_SCREEN_DASH_WIDTH_PX * 0.75)
#define C20x_SCREEN_DASH_LABEL_HEIGHT_MAX	(C20X_SCREEN_DASH_HEIGHT_PX / C20X_SCREEN_DASH_NUM_LABELS_TO_DISP)
#define C20x_SCREEN_DASH_ICON_WIDTH			(20)
#define C20x_SCREEN_DASH_ICON_HEIGHT		(20)
#elif (CONFIG_C20X_SCREENS_TFT)
#define C20x_SCREEN_DASH_LABEL_WIDTH_MAX	(C20X_SCREEN_DASH_WIDTH_PX * 0.75)
#define C20x_SCREEN_DASH_LABEL_HEIGHT_MAX	(C20X_SCREEN_DASH_HEIGHT_PX / C20X_SCREEN_DASH_NUM_LABELS_TO_DISP)
#define C20x_SCREEN_DASH_ICON_WIDTH			(20)
#define C20x_SCREEN_DASH_ICON_HEIGHT		(20)
#endif

/* settings screen */
#define C20X_SCREEN_SETTINGS_SWITCH_WIDTH_PX		(40)
#define C20X_SCREEN_SETTINGS_SWITCH_HEIGHT_PX		(20)
#define C20X_SCREEN_SETTINGS_LABEL_HEIGHT_PERCENT	(18)
#define C20X_SCREEN_SETTINGS_LABEL_HEIGHT_PX		C20X_SCREEN_SBAR_HEIGHT_PX //10 //((APP_DISPLAY_HEIGHT_PX * C20X_SCREEN_SETTINGS_LABEL_HEIGHT_PERCENT) / 100)
#define C20X_SCREEN_SETTINGS_WIDTH_PX				APP_DISPLAY_WIDTH_PX
#define C20X_SCREEN_SETTINGS_HEIGHT_PX				(APP_DISPLAY_HEIGHT_PX - C20X_SCREEN_SETTINGS_LABEL_HEIGHT_PX)

/* menu list */
#if (CONFIG_C20X_SCREENS_OLED)
	#define C20x_SCREEN_LIST_BORDER_WIDTH		(1)
	#define C20x_SCREEN_LIST_PADDING			(4)
	#define C20x_SCREEN_LIST_PADDING_RIGHT		(C20x_SCREEN_LIST_PADDING + (8))
	#define C20x_SCREEN_LISTBTN_BORDER_WIDTH	(1)
	#define C20x_SCREEN_LISTBTN_PADDING			(0)
	#define C20x_SCREEN_LISTBTN_PADDING_RIGHT	C20x_SCREEN_LISTBTN_PADDING	+ (8)
	#define C20X_SCREEN_SCROLLBAR_WIDTH			(2)
	#define C20x_SCREEN_LISTBTN_TEXT_LEN_MAX	(18)
#elif (CONFIG_C20X_SCREENS_TFT)
	#define C20x_SCREEN_LISTBTN_TEXT_LEN_MAX	(50)
#endif
/* spinbox */
#define C20X_SCREEN_SPINBOX_WIDTH_PX		(50)
#define C20X_SCREEN_SPINBOX_HEIGHT_PX		(20)

/* roller */
#define C20X_SCREEN_ROLLER_SCREEN_WIDTH_PX		(128)
#define C20X_SCREEN_ROLLER_SCREEN_HEIGHT_PX		(APP_DISPLAY_HEIGHT_PX -C20X_SCREEN_SETTINGS_LABEL_HEIGHT_PX)
#define C20x_SCREEN_ROLLER_PADDING_SIDE			(2)
#define C20x_SCREEN_ROLLER_PADDING_MID			(2)
#define C20x_SCREEN_ROLLER_PADDING_BOTTOM		(-2)

/* date time */
#define C20X_SCREEN_DATETIME_YEAR_MIN		(2023)
#define C20X_SCREEN_DATETIME_YEAR_MAX		(2040)
#define C20X_SCREEN_DATETIME_ROLLER_WIDTH_PX	(40)
#define C20X_SCREEN_DATETIME_ROLLER_VISIBLE		(3)

/* alert / msg box */
#if (CONFIG_C20X_SCREENS_OLED)
#define C20X_SCREEN_ALERT_MSG_BTN_MATRIX_HEIGHT_PX		(12)
#elif (CONFIG_C20X_SCREENS_TFT)
#define C20X_SCREEN_ALERT_MSG_BTN_MATRIX_HEIGHT_PX		(30)
#endif
#endif /* SRC_APP_APP_DISPLAY_C20X_SCREENS_C20X_SCREEN_CONFIG_H_ */
