/*
 * Copyright (c) 2022 Acme CPU
 *
 *  Created on: 17-Jan-2023
 *      Author: Rohan Dey (rohan@acmecpu.com)
 */

#ifndef SRC_INCLUDE_APP_PUSH_SWITCH_APP_PUSH_SWITCH_H_
#define SRC_INCLUDE_APP_PUSH_SWITCH_APP_PUSH_SWITCH_H_

#include "lib_push_switch/lib_push_switch.h"

#define APP_MAX_PUSH_SWITCH	    CONFIG_PUSH_SWITCH_MAX_COUNT

#if (CONFIG_BOARD_STM32G473_ACME_CPU_C201_OLED || CONFIG_BOARD_STM32G473_ACME_CPU_C201)

#define APP_PUSH_SWITCH_DEVICE_ENTER	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_1), gpios))
#define APP_PUSH_SWITCH_DEVICE_BACK		DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_2), gpios))
#define APP_PUSH_SWITCH_DEVICE_LEFT		DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_3), gpios))
#define APP_PUSH_SWITCH_DEVICE_POWER	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_4), gpios))
#define APP_PUSH_SWITCH_DEVICE_RIGHT	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_5), gpios))
#define APP_PUSH_SWITCH_DEVICE_DOWN	    DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_6), gpios))
#define APP_PUSH_SWITCH_DEVICE_UP		DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_7), gpios))

//#define APP_PUSH_SWITCH_LABEL_POWER	    DT_GPIO_LABEL(DT_NODELABEL(switch_1), gpios)
//#define APP_PUSH_SWITCH_LABEL_CANCEL	DT_GPIO_LABEL(DT_NODELABEL(switch_2), gpios)
//#define APP_PUSH_SWITCH_LABEL_HOME		DT_GPIO_LABEL(DT_NODELABEL(switch_3), gpios)
//#define APP_PUSH_SWITCH_LABEL_NO	    DT_GPIO_LABEL(DT_NODELABEL(switch_4), gpios)
//#define APP_PUSH_SWITCH_LABEL_YES	    DT_GPIO_LABEL(DT_NODELABEL(switch_5), gpios)
//#define APP_PUSH_SWITCH_LABEL_ENTER	    DT_GPIO_LABEL(DT_NODELABEL(switch_6), gpios)
//#define APP_PUSH_SWITCH_LABEL_MIC		DT_GPIO_LABEL(DT_NODELABEL(switch_7), gpios)
//#define APP_PUSH_SWITCH_LABEL_SAVE		DT_GPIO_LABEL(DT_NODELABEL(switch_8), gpios)

#define APP_PUSH_SWITCH_PIN_ENTER		DT_GPIO_PIN(DT_NODELABEL(switch_1), gpios)
#define APP_PUSH_SWITCH_PIN_BACK		DT_GPIO_PIN(DT_NODELABEL(switch_2), gpios)
#define APP_PUSH_SWITCH_PIN_LEFT		DT_GPIO_PIN(DT_NODELABEL(switch_3), gpios)
#define APP_PUSH_SWITCH_PIN_POWER	    DT_GPIO_PIN(DT_NODELABEL(switch_4), gpios)
#define APP_PUSH_SWITCH_PIN_RIGHT	    DT_GPIO_PIN(DT_NODELABEL(switch_5), gpios)
#define APP_PUSH_SWITCH_PIN_DOWN		DT_GPIO_PIN(DT_NODELABEL(switch_6), gpios)
#define APP_PUSH_SWITCH_PIN_UP		    DT_GPIO_PIN(DT_NODELABEL(switch_7), gpios)

#define APP_PUSH_SWITCH_FLAGS_ENTER    	(GPIO_INPUT | GPIO_INT_EDGE_FALLING 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_1), gpios))
#define APP_PUSH_SWITCH_FLAGS_BACK		(GPIO_INPUT | GPIO_INT_EDGE_FALLING		| DT_GPIO_FLAGS(DT_NODELABEL(switch_2), gpios))
#define APP_PUSH_SWITCH_FLAGS_LEFT	    (GPIO_INPUT | GPIO_INT_LEVEL_LOW 		| DT_GPIO_FLAGS(DT_NODELABEL(switch_3), gpios))
#define APP_PUSH_SWITCH_FLAGS_POWER    	(GPIO_INPUT | GPIO_INT_EDGE_FALLING 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_4), gpios))
#define APP_PUSH_SWITCH_FLAGS_RIGHT    	(GPIO_INPUT | GPIO_INT_LEVEL_LOW 		| DT_GPIO_FLAGS(DT_NODELABEL(switch_5), gpios))
#define APP_PUSH_SWITCH_FLAGS_DOWN		(GPIO_INPUT | GPIO_INT_LEVEL_LOW 		| DT_GPIO_FLAGS(DT_NODELABEL(switch_6), gpios))
#define APP_PUSH_SWITCH_FLAGS_UP		(GPIO_INPUT | GPIO_INT_LEVEL_LOW 		| DT_GPIO_FLAGS(DT_NODELABEL(switch_7), gpios))

#define APP_PUSH_SWITCH_MASK_ENTER		(1 << APP_PUSH_SWITCH_PIN_ENTER)
#define APP_PUSH_SWITCH_MASK_BACK	    (1 << APP_PUSH_SWITCH_PIN_BACK)
#define APP_PUSH_SWITCH_MASK_LEFT		(1 << APP_PUSH_SWITCH_PIN_LEFT)
#define APP_PUSH_SWITCH_MASK_POWER		(1 << APP_PUSH_SWITCH_PIN_POWER)
#define APP_PUSH_SWITCH_MASK_RIGHT		(1 << APP_PUSH_SWITCH_PIN_RIGHT)
#define APP_PUSH_SWITCH_MASK_DOWN		(1 << APP_PUSH_SWITCH_PIN_DOWN)
#define APP_PUSH_SWITCH_MASK_UP			(1 << APP_PUSH_SWITCH_PIN_UP)

#define APP_PUSH_SWITCH_HASINTR_ENTER		true
#define APP_PUSH_SWITCH_HASINTR_BACK	    true
#define APP_PUSH_SWITCH_HASINTR_DOWN		true
#define APP_PUSH_SWITCH_HASINTR_POWER		true
#define APP_PUSH_SWITCH_HASINTR_RIGHT		true
#define APP_PUSH_SWITCH_HASINTR_LEFT		true
#define APP_PUSH_SWITCH_HASINTR_UP			true

#define APP_PUSH_SWITCH_MASK_ALL_ASSERTED		(APP_PUSH_SWITCH_MASK_ENTER \
												| APP_PUSH_SWITCH_MASK_BACK \
												| APP_PUSH_SWITCH_MASK_LEFT \
												| APP_PUSH_SWITCH_MASK_POWER \
												| APP_PUSH_SWITCH_MASK_RIGHT \
												| APP_PUSH_SWITCH_MASK_DOWN \
												| APP_PUSH_SWITCH_MASK_UP \
)

#define APP_PUSH_SWITCH_PRESS_ACTION_INIT_DATA \
{ \
	{APP_PUSH_SWITCH_DEVICE_ENTER, APP_PUSH_SWITCH_MASK_ENTER, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_ENTER},\
	{APP_PUSH_SWITCH_DEVICE_BACK, APP_PUSH_SWITCH_MASK_BACK, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_BACK}, \
	{APP_PUSH_SWITCH_DEVICE_LEFT, APP_PUSH_SWITCH_MASK_LEFT, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_LEFT}, \
	{APP_PUSH_SWITCH_DEVICE_POWER, APP_PUSH_SWITCH_MASK_POWER, SWITCH_PRESSED_NORMAL_EDGE_LONG, false, 0, APP_PUSH_SWITCH_PIN_POWER}, \
	{APP_PUSH_SWITCH_DEVICE_RIGHT, APP_PUSH_SWITCH_MASK_RIGHT, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_RIGHT}, \
    {APP_PUSH_SWITCH_DEVICE_DOWN, APP_PUSH_SWITCH_MASK_DOWN, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_DOWN}, \
	{APP_PUSH_SWITCH_DEVICE_UP, APP_PUSH_SWITCH_MASK_UP, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_UP}, \
}

#elif (CONFIG_BOARD_C204_CORE || CONFIG_BOARD_C205)

#define APP_PUSH_SWITCH_DEVICE_ENTER	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_1), gpios))
#define APP_PUSH_SWITCH_DEVICE_BACK		DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_2), gpios))
#define APP_PUSH_SWITCH_DEVICE_DOWN	    DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_3), gpios))
#define APP_PUSH_SWITCH_DEVICE_POWER	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_4), gpios))
#define APP_PUSH_SWITCH_DEVICE_RIGHT	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_5), gpios))
#define APP_PUSH_SWITCH_DEVICE_LEFT		DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_6), gpios))
#define APP_PUSH_SWITCH_DEVICE_UP		DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_7), gpios))
#define APP_PUSH_SWITCH_DEVICE_HOME	    DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_8), gpios))

//#define APP_PUSH_SWITCH_LABEL_POWER	    DT_GPIO_LABEL(DT_NODELABEL(switch_1), gpios)
//#define APP_PUSH_SWITCH_LABEL_CANCEL	DT_GPIO_LABEL(DT_NODELABEL(switch_2), gpios)
//#define APP_PUSH_SWITCH_LABEL_HOME		DT_GPIO_LABEL(DT_NODELABEL(switch_3), gpios)
//#define APP_PUSH_SWITCH_LABEL_NO	    DT_GPIO_LABEL(DT_NODELABEL(switch_4), gpios)
//#define APP_PUSH_SWITCH_LABEL_YES	    DT_GPIO_LABEL(DT_NODELABEL(switch_5), gpios)
//#define APP_PUSH_SWITCH_LABEL_ENTER	    DT_GPIO_LABEL(DT_NODELABEL(switch_6), gpios)
//#define APP_PUSH_SWITCH_LABEL_MIC		DT_GPIO_LABEL(DT_NODELABEL(switch_7), gpios)
//#define APP_PUSH_SWITCH_LABEL_SAVE		DT_GPIO_LABEL(DT_NODELABEL(switch_8), gpios)

#define APP_PUSH_SWITCH_PIN_ENTER		DT_GPIO_PIN(DT_NODELABEL(switch_1), gpios)
#define APP_PUSH_SWITCH_PIN_BACK		DT_GPIO_PIN(DT_NODELABEL(switch_2), gpios)
#define APP_PUSH_SWITCH_PIN_DOWN		DT_GPIO_PIN(DT_NODELABEL(switch_3), gpios)
#define APP_PUSH_SWITCH_PIN_POWER	    DT_GPIO_PIN(DT_NODELABEL(switch_4), gpios)
#define APP_PUSH_SWITCH_PIN_RIGHT	    DT_GPIO_PIN(DT_NODELABEL(switch_5), gpios)
#define APP_PUSH_SWITCH_PIN_LEFT		DT_GPIO_PIN(DT_NODELABEL(switch_6), gpios)
#define APP_PUSH_SWITCH_PIN_UP		    DT_GPIO_PIN(DT_NODELABEL(switch_7), gpios)
#define APP_PUSH_SWITCH_PIN_HOME		DT_GPIO_PIN(DT_NODELABEL(switch_8), gpios)

#define APP_PUSH_SWITCH_FLAGS_ENTER    	(GPIO_INPUT | GPIO_INT_LEVEL_LOW 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_1), gpios))
#define APP_PUSH_SWITCH_FLAGS_BACK		(GPIO_INPUT | GPIO_INT_LEVEL_LOW 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_2), gpios))
#define APP_PUSH_SWITCH_FLAGS_DOWN		(GPIO_INPUT | GPIO_INT_LEVEL_LOW 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_3), gpios))
#define APP_PUSH_SWITCH_FLAGS_POWER    	(GPIO_INPUT | GPIO_INT_EDGE_FALLING | DT_GPIO_FLAGS(DT_NODELABEL(switch_4), gpios))
#define APP_PUSH_SWITCH_FLAGS_RIGHT    	(GPIO_INPUT | GPIO_INT_LEVEL_LOW 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_5), gpios))
#define APP_PUSH_SWITCH_FLAGS_LEFT	    (GPIO_INPUT | GPIO_INT_LEVEL_LOW 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_6), gpios))
#define APP_PUSH_SWITCH_FLAGS_UP		(GPIO_INPUT | GPIO_INT_LEVEL_LOW 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_7), gpios))
#define APP_PUSH_SWITCH_FLAGS_HOME		(GPIO_INPUT | GPIO_INT_LEVEL_LOW 	| DT_GPIO_FLAGS(DT_NODELABEL(switch_8), gpios))

#define APP_PUSH_SWITCH_MASK_ENTER		(1 << APP_PUSH_SWITCH_PIN_ENTER)
#define APP_PUSH_SWITCH_MASK_BACK	    (1 << APP_PUSH_SWITCH_PIN_BACK)
#define APP_PUSH_SWITCH_MASK_DOWN		(1 << APP_PUSH_SWITCH_PIN_DOWN)
#define APP_PUSH_SWITCH_MASK_POWER		(1 << APP_PUSH_SWITCH_PIN_POWER)
#define APP_PUSH_SWITCH_MASK_RIGHT		(1 << APP_PUSH_SWITCH_PIN_RIGHT)
#define APP_PUSH_SWITCH_MASK_LEFT		(1 << APP_PUSH_SWITCH_PIN_LEFT)
#define APP_PUSH_SWITCH_MASK_UP			(1 << APP_PUSH_SWITCH_PIN_UP)
#define APP_PUSH_SWITCH_MASK_HOME		(1 << APP_PUSH_SWITCH_PIN_HOME)

#define APP_PUSH_SWITCH_HASINTR_ENTER		false
#define APP_PUSH_SWITCH_HASINTR_BACK	    false
#define APP_PUSH_SWITCH_HASINTR_DOWN		false
#define APP_PUSH_SWITCH_HASINTR_POWER		true
#define APP_PUSH_SWITCH_HASINTR_RIGHT		false
#define APP_PUSH_SWITCH_HASINTR_LEFT		false
#define APP_PUSH_SWITCH_HASINTR_UP			false
#define APP_PUSH_SWITCH_HASINTR_HOME		false

#define APP_PUSH_SWITCH_MASK_ALL_ASSERTED		(APP_PUSH_SWITCH_MASK_ENTER \
												| APP_PUSH_SWITCH_MASK_BACK \
												| APP_PUSH_SWITCH_MASK_DOWN \
												| APP_PUSH_SWITCH_MASK_POWER \
												| APP_PUSH_SWITCH_MASK_RIGHT \
												| APP_PUSH_SWITCH_MASK_LEFT \
												| APP_PUSH_SWITCH_MASK_UP \
												| APP_PUSH_SWITCH_MASK_HOME \
)

#define APP_PUSH_SWITCH_PRESS_ACTION_INIT_DATA \
{ \
	{APP_PUSH_SWITCH_DEVICE_ENTER, APP_PUSH_SWITCH_MASK_ENTER, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_ENTER},\
	{APP_PUSH_SWITCH_DEVICE_BACK, APP_PUSH_SWITCH_MASK_BACK, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_BACK}, \
    {APP_PUSH_SWITCH_DEVICE_DOWN, APP_PUSH_SWITCH_MASK_DOWN, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_DOWN}, \
	{APP_PUSH_SWITCH_DEVICE_POWER, APP_PUSH_SWITCH_MASK_POWER, SWITCH_PRESSED_NORMAL_EDGE_LONG, false, 0, APP_PUSH_SWITCH_PIN_POWER}, \
	{APP_PUSH_SWITCH_DEVICE_RIGHT, APP_PUSH_SWITCH_MASK_RIGHT, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_RIGHT}, \
	{APP_PUSH_SWITCH_DEVICE_LEFT, APP_PUSH_SWITCH_MASK_LEFT, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_LEFT}, \
	{APP_PUSH_SWITCH_DEVICE_UP, APP_PUSH_SWITCH_MASK_UP, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_UP}, \
	{APP_PUSH_SWITCH_DEVICE_HOME, APP_PUSH_SWITCH_MASK_HOME, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_HOME}, \
}

/* #elif (CONFIG_BOARD_C204_CORE || CONFIG_BOARD_C205) */

#elif (CONFIG_BOARD_E206 || CONFIG_BOARD_C208T)

#define APP_PUSH_SWITCH_DEVICE_POWER	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_1), gpios))
#define APP_PUSH_SWITCH_PIN_POWER	    DT_GPIO_PIN(DT_NODELABEL(switch_1), gpios)
#define APP_PUSH_SWITCH_FLAGS_POWER    	(GPIO_INPUT | GPIO_INT_EDGE_FALLING | DT_GPIO_FLAGS(DT_NODELABEL(switch_1), gpios))
#define APP_PUSH_SWITCH_MASK_POWER		(1 << APP_PUSH_SWITCH_PIN_POWER)
#define APP_PUSH_SWITCH_HASINTR_POWER		true
#define APP_PUSH_SWITCH_MASK_ALL_ASSERTED		(APP_PUSH_SWITCH_MASK_POWER)
#define APP_PUSH_SWITCH_PRESS_ACTION_INIT_DATA \
{ \
	{APP_PUSH_SWITCH_DEVICE_POWER, APP_PUSH_SWITCH_MASK_POWER, SWITCH_PRESSED_NORMAL_EDGE_LONG, false, 0, APP_PUSH_SWITCH_PIN_POWER}, \
}
/* #elif (CONFIG_BOARD_E206) */

#endif /*#if (CONFIG_BOARD_STM32G473_ACME_CPU_C201_OLED || CONFIG_BOARD_STM32G473_ACME_CPU_C201)*/

/**
 * @brief	Returns the logical pin status of power key
 * @return
 * 		0		the power key is not pressed
 * 		1		the power key is pressed
 */
int app_push_switch_state_get_power_key();
int app_push_switch_init();

#endif /* SRC_INCLUDE_APP_PUSH_SWITCH_APP_PUSH_SWITCH_H_ */
