#-------------------------------------------------------------- Build specific configs
#CONFIG_DEVICE_HANDLE_PADDING=1

#-------------------------------------------------------------- Zephyr specific configs
CONFIG_REBOOT=y
#CONFIG_LEGACY_INCLUDE_PATH=y

#-------------------------------------------------------------- ARM specific configs
CONFIG_FPU=y

#-------------------------------------------------------------- System monitoring - Thread analyzer configs
#CONFIG_THREAD_ANALYZER=y
#CONFIG_THREAD_ANALYZER_USE_LOG=y
#CONFIG_THREAD_ANALYZER_USE_PRINTK=y
#CONFIG_THREAD_ANALYZER_AUTO=y
#CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=10

#-------------------------------------------------------------- Compiler configurations
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_LOG=y
CONFIG_PRINTK=y

# Add this section to the prj.conf file
# Currently ther is a half way through implementation of a 
# TIM Input Capture callback function in the bsp_fan.c file
# which utilizes a ring buffer. Might not need this in the future
# (DMA would do the work better)

#CONFIG_RING_BUFFER=y
