/*
 * Copyright (c) 2021 Acme CPU
 */

#ifndef SRC_INCLUDE_ACPU_C201_MODULES_H_
#define SRC_INCLUDE_ACPU_C201_MODULES_H_

#if (CONFIG_BOARD_STM32G473_ACME_CPU_C201_OLED || CONFIG_BOARD_STM32G473_ACME_CPU_C201 || CONFIG_BOARD_C204_CORE)
#define ACPU_C201_MOD_NAME_BLOWER			"SYS FAN"
#endif
#if (CONFIG_TPS55340)
	#define ACPU_C201_MOD_NAME_BOOST			"BOOST CONVERTER"
#endif
#define ACPU_C201_MOD_NAME_BATTERY_CHRG		"BATT_CHRG"
#define ACPU_C201_MOD_NAME_BUZZER			"BUZZER"
#define ACPU_C201_MOD_NAME_NWPROC_COM_PORT	"UART_3"
#define ACPU_C201_MOD_NAME_RTC				"LP_RTC"
#define ACPU_C201_MOD_NAME_STM32_FLASH_OB	"STM32_FLASH_OB"
#define ACPU_C201_MOD_NAME_STEPPER			"STSPIN220"
#define ACPU_C201_MOD_NAME_STEPPER_2		"STSPIN220_2"
//#define ACPU_C201_MOD_NAME_UCPD				"UCPD"
#define ACPU_C201_MOD_NAME_DISPLAY_PWR		"DISPLAY_PWR"
//#define ACPU_C201_MOD_NAME_SENS_PRESS_TEST	"PRESS_TEST"
#define ACPU_C201_MOD_NAME_SENS_PRESS_INT_POS	"PS_INT_POS"
#define ACPU_C201_MOD_NAME_SENS_PRESS_INT_NEG	"PS_INT_NEG"
#define ACPU_C201_MOD_NAME_SENS_PRESS_EXT_POS	"PS_EXT_POS"
#define ACPU_C201_MOD_NAME_SENS_PRESS_EXT_NEG	"PS_EXT_NEG"
#define ACPU_C201_MOD_NAME_SENS_HUMIDITY_S203		"HUMID_S203"
#define ACPU_C201_MOD_NAME_SENS_TILT		"TILT_SENSOR"
#define ACPU_C201_MOD_NAME_SENS_IMU_1		"IMU_1"
#define ACPU_C201_MOD_NAME_PERIPH_RST		"PERIPH RST"
#define ACPU_C201_MOD_NAME_WIFI_BT_IF		DT_PROP(DT_ALIAS(wifibt_serial), label)	//"UART_n"
#if (CONFIG_BOARD_C204_CORE || CONFIG_BOARD_C205 || CONFIG_BOARD_E206 || CONFIG_BOARD_C208T)
#define ACPU_C201_MOD_NAME_BLDC_DRV_IF		DT_PROP(DT_ALIAS(bldc_drv_serial), label)	//"UART_n"
#endif
#define ACPU_C201_MOD_NAME_FUEL_GAUGE		"FG"
#define ACPU_NTC1_THERMISTOR "ACPU_NTC_1"
#define ACPU_NTC2_THERMISTOR "ACPU_NTC_2"
#define ACPU_FLUID_LEVEL "ACPU_FLUID_LEVEL"

/* LED names */
//#define ACPU_C201_MOD_NAME_LED_DRV			"UI_LEDS"
//#define ACPU_C201_MOD_NAME_LED_POWER		"POWER_LED"
//#define ACPU_C201_MOD_NAME_LED_SYS_ON		"SYS_ON_LED"
//#define ACPU_C201_MOD_NAME_LED_SYS_FAULT	"SYS_FAULT_LED"
//#define ACPU_C201_MOD_NAME_LED_RESERVED		"RESERVED_LED"

typedef enum {
	UART_COM_WIFI_BT = 0,
	UART_COM_MOTOR_DRV,
	UART_COM_LTE_MODEM,
} UART_COM_DEVICE;

#endif /* SRC_INCLUDE_ACPU_C201_MODULES_H_ */
