/*
 * Copyright (c) 2021 Acme CPU
 */



#ifndef SRC_INCLUDE_APP_THREAD_CONFIGS_H_
#define SRC_INCLUDE_APP_THREAD_CONFIGS_H_


/* Application thread priorities */
#define APP_THREAD_PRIO_MEMBR_SWITCH_PRESS_DETECT		1
#define APP_THREAD_PRIO_MEMBR_SWITCH					1
//#define APP_THREAD_PRIO_EVENT_CAPTURE					2
#define APP_THREAD_PRIO_BLOWER_PID						3
#define APP_THREAD_PRIO_PID								1
#define APP_THREAD_PRIO_STEPPER							4
#define APP_THREAD_PRIO_DISPLAY_REFRESH					5
//#define APP_THREAD_PRIO_LED_NTF						10
#define APP_THREAD_PRIO_WIFI_BT							8
#if (CONFIG_BOARD_C204_CORE || CONFIG_BOARD_C205 || CONFIG_BOARD_E206 || CONFIG_BOARD_C208T)
#define APP_THREAD_PRIO_BLDC_DRV						2
#endif
#define APP_THREAD_PRIO_NET								6
#define APP_THREAD_PRIO_HTMLGEN							7
#define APP_THREAD_PRIO_DFU_NETPROC						10
#define APP_THREAD_PRIO_SENSOR_LIST						8

/* Application thread stack sizes */
//#define APP_THREAD_STACK_SIZE_MEMBR_SWITCH_PRESS_DETECT	(512)
//#define APP_THREAD_STACK_SIZE_MEMBR_SWITCH				(1024)
#if (CONFIG_BOARD_E206 || CONFIG_BOARD_C208T)
#define APP_THREAD_STACK_SIZE_DISPLAY_REFRESH				(4*1024)
#else
#define APP_THREAD_STACK_SIZE_DISPLAY_REFRESH				(2*1024)
#endif
//#define APP_THREAD_STACK_SIZE_BLOWER_PID					(2*1024)
#define APP_THREAD_STACK_SIZE_PID							(2*1024)
#define APP_THREAD_STACK_SIZE_SENSOR_LIST					(2*1024)
//#define APP_THREAD_STACK_SIZE_EVENT_CAPTURE				(512)
//#define APP_THREAD_STACK_SIZE_LED_NTF						(512)
#if (CONFIG_BOARD_STM32G473_ACME_CPU_C201_OLED || CONFIG_BOARD_STM32G473_ACME_CPU_C201)
	#define APP_THREAD_STACK_SIZE_STEPPER					(1024)
#elif (CONFIG_BOARD_C204_CORE || CONFIG_BOARD_C205 || CONFIG_BOARD_E206)
	#define APP_THREAD_STACK_SIZE_STEPPER					(512)
#endif
#define APP_THREAD_STACK_SIZE_WIFI_BT						(4*1024)
#if (CONFIG_BOARD_C204_CORE || CONFIG_BOARD_C205)
#define APP_THREAD_STACK_SIZE_BLDC_DRV						(2*1024) //(1536)
#elif (CONFIG_BOARD_E206 || CONFIG_BOARD_C208T)
#define APP_THREAD_STACK_SIZE_BLDC_DRV						(4*1024)
#endif
#define APP_THREAD_STACK_SIZE_NET							(3*1024)
#define APP_THREAD_STACK_SIZE_HTMLGEN						(2*1024)
#define APP_THREAD_STACK_SIZE_DFU_NETPROC					(4*1024)

/* Application thread names */
#define APP_THREAD_NAME_MEMBR_SWITCH_PRESS_DETECT		"swdt"
#define APP_THREAD_NAME_MEMBR_SWITCH					"swch"
//#define APP_THREAD_NAME_EVENT_CAPTURE					"evnt"
#define APP_THREAD_NAME_BLOWER_PID						"blow"
#define APP_THREAD_NAME_PID								"pid"
#define APP_THREAD_NAME_STEPPER							"step"
#define APP_THREAD_NAME_DISPLAY_REFRESH					"disp"
//#define APP_THREAD_NAME_LED_NTF						"led"
#define APP_THREAD_NAME_WIFI_BT							"wifi_bt"
#if (CONFIG_BOARD_C204_CORE || CONFIG_BOARD_C205 || CONFIG_BOARD_E206 || CONFIG_BOARD_C208T)
#define APP_THREAD_NAME_BLDC_DRV						"bldc_drv"
#endif
#define APP_THREAD_NAME_NET								"net"
#define APP_THREAD_NAME_24W_P							"24wp"
#define APP_THREAD_NAME_12W_P							"12wp"
#define APP_THREAD_NAME_HTMLGEN							"html"
#define APP_THREAD_NAME_DFU_NETPROC						"dfu_net"
#define APP_THREAD_NAME_SENSOR_LIST_P                   "senlist"

#endif /* SRC_INCLUDE_APP_THREAD_CONFIGS_H_ */
