/*
 * Copyright (c) 2023 Acme CPU
 *
 *  Created on: 10-Feb-2023
 *      Author: Rohan Dey (rohan@acmecpu.com)
 */

#ifndef SRC_INCLUDE_APP_SETTINGS_APP_SETTINGS_PATHS_H_
#define SRC_INCLUDE_APP_SETTINGS_APP_SETTINGS_PATHS_H_

#define SETTINGS_FULLPATH_LEN_MAX		32

#define SETTINGS_KEY_YR       "yr"
#define SETTINGS_KEY_MON      "mon"
#define SETTINGS_KEY_DAY      "day"
#define SETTINGS_KEY_HR       "hr"
#define SETTINGS_KEY_MIN      "min"
//#define SETTINGS_KEY_SEC      "sec"

#define SETTINGS_KEY_ROOT			"r"
#define SETTINGS_SEPARATOR			"/"

/********************************************************************
 * The below macros are generated by codegen. Do not edit them!
 *********************************************************************/

#define SETTINGS_KEY_FULL_NAM        "r/nam"
#define SETTINGS_KEY_FULL_BST        "r/bst"
#define SETTINGS_KEY_FULL_DEV        "r/dev"
#define SETTINGS_KEY_FULL_DEV_BMODE        "r/dev/bmode"
#define SETTINGS_KEY_FULL_DEV_BRPM        "r/dev/brpm"
#define SETTINGS_KEY_FULL_DEV_BRAMP        "r/dev/bramp"
#define SETTINGS_KEY_FULL_DEV_USB        "r/dev/usb"
#define SETTINGS_KEY_FULL_TS        "r/ts"
#define SETTINGS_KEY_FULL_TS_MOD        "r/ts/mod"
#define SETTINGS_KEY_FULL_TS_FIC        "r/ts/fic"
#define SETTINGS_KEY_FULL_TS_MNC        "r/ts/mnc"
#define SETTINGS_KEY_FULL_TS_MXC        "r/ts/mxc"
#define SETTINGS_KEY_FULL_TS_MXI        "r/ts/mxi"
#define SETTINGS_KEY_FULL_TS_IPA        "r/ts/ipa"
#define SETTINGS_KEY_FULL_TS_FXE        "r/ts/fxe"
#define SETTINGS_KEY_FULL_TS_MNE        "r/ts/mne"
#define SETTINGS_KEY_FULL_TS_PRS        "r/ts/prs"
#define SETTINGS_KEY_FULL_TS_RR        "r/ts/rr"
#define SETTINGS_KEY_FULL_TS_RIT        "r/ts/rit"
#define SETTINGS_KEY_FULL_TS_FXT        "r/ts/fxt"
#define SETTINGS_KEY_FULL_TS_MXT        "r/ts/mxt"
#define SETTINGS_KEY_FULL_TS_MNT        "r/ts/mnt"
#define SETTINGS_KEY_FULL_TS_EDT        "r/ts/edt"
#define SETTINGS_KEY_FULL_DS        "r/ds"
#define SETTINGS_KEY_FULL_DS_SRN        "r/ds/srn"
#define SETTINGS_KEY_FULL_DS_DAT        "r/ds/dat"
#define SETTINGS_KEY_FULL_DS_DAT_YR        "r/ds/dat/yr"
#define SETTINGS_KEY_FULL_DS_DAT_MON        "r/ds/dat/mon"
#define SETTINGS_KEY_FULL_DS_DAT_DAY        "r/ds/dat/day"
#define SETTINGS_KEY_FULL_DS_TIM        "r/ds/tim"
#define SETTINGS_KEY_FULL_DS_TIM_HR        "r/ds/tim/hr"
#define SETTINGS_KEY_FULL_DS_TIM_MIN        "r/ds/tim/min"
#define SETTINGS_KEY_FULL_DS_FRS        "r/ds/frs"
#define SETTINGS_KEY_FULL_DS_PAE        "r/ds/pae"
#define SETTINGS_KEY_FULL_DS_ERD        "r/ds/erd"
#define SETTINGS_KEY_FULL_DS_LAN        "r/ds/lan"
#define SETTINGS_KEY_FULL_DS_NET        "r/ds/net"
#define SETTINGS_KEY_FULL_DS_NET_WIAP        "r/ds/net/wiap"
#define SETTINGS_KEY_FULL_DS_NET_WPWD        "r/ds/net/wpwd"
#define SETTINGS_KEY_FULL_DS_NET_WSTACFG        "r/ds/net/wstacfg"
#define SETTINGS_KEY_FULL_DS_NET_WMAC        "r/ds/net/wmac"
#define SETTINGS_KEY_FULL_DS_NET_WIP        "r/ds/net/wip"
#define SETTINGS_KEY_FULL_DS_NET_WSSID        "r/ds/net/wssid"
#define SETTINGS_KEY_FULL_DS_NET_WSSIDCON        "r/ds/net/wssidcon"
#define SETTINGS_KEY_FULL_DS_NET_WI        "r/ds/net/wi"
#define SETTINGS_KEY_FULL_CS        "r/cs"
#define SETTINGS_KEY_FULL_CS_POU        "r/cs/pou"
#define SETTINGS_KEY_FULL_CS_HUM        "r/cs/hum"
#define SETTINGS_KEY_FULL_CS_RTM        "r/cs/rtm"
#define SETTINGS_KEY_FULL_CS_STM        "r/cs/stm"
#define SETTINGS_KEY_FULL_CS_AON        "r/cs/aon"
#define SETTINGS_KEY_FULL_CS_AOF        "r/cs/aof"
#define SETTINGS_KEY_FULL_CS_LAL        "r/cs/lal"
#define SETTINGS_KEY_FULL_CS_HET        "r/cs/het"
#define SETTINGS_KEY_FULL_CS_HET_W24        "r/cs/het/w24"
#define SETTINGS_KEY_FULL_CS_HET_W24HST        "r/cs/het/w24/hst"
#define SETTINGS_KEY_FULL_CS_HET_W24HUM        "r/cs/het/w24/hum"
#define SETTINGS_KEY_FULL_CS_HET_W12        "r/cs/het/w12"
#define SETTINGS_KEY_FULL_CS_HET_W12HST        "r/cs/het/w12/hst"
#define SETTINGS_KEY_FULL_CS_HET_W12TEMP        "r/cs/het/w12/temp"
#define SETTINGS_KEY_FULL_CS_SP        "r/cs/sp"
#define SETTINGS_KEY_FULL_CS_SP_PRESS        "r/cs/sp/press"
#define SETTINGS_KEY_FULL_CS_SP_PRESSINW        "r/cs/sp/press/inw"
#define SETTINGS_KEY_FULL_CS_SP_PRESSINPT        "r/cs/sp/press/inpt"
#define SETTINGS_KEY_FULL_CS_SP_PRESSEXW        "r/cs/sp/press/exw"
#define SETTINGS_KEY_FULL_CS_SP_PRESSEXPT        "r/cs/sp/press/expt"
#define SETTINGS_KEY_FULL_CS_SP_PRESSAMB        "r/cs/sp/press/amb"
#define SETTINGS_KEY_FULL_CS_SP_HUMI        "r/cs/sp/humi"
#define SETTINGS_KEY_FULL_CS_SP_HUMIINCH        "r/cs/sp/humi/inch"
#define SETTINGS_KEY_FULL_CS_SP_DIST        "r/cs/sp/dist"
#define SETTINGS_KEY_FULL_CS_SP_DISTWCH        "r/cs/sp/dist/wch"
#define SETTINGS_KEY_FULL_AS        "r/as"
#define SETTINGS_KEY_FULL_AS_LAL        "r/as/lal"
#define SETTINGS_KEY_FULL_AS_BS        "r/as/bs"
#define SETTINGS_KEY_FULL_AS_TRG        "r/as/trg"
#define SETTINGS_KEY_FULL_AS_CYC        "r/as/cyc"
#define SETTINGS_KEY_FULL_AS_TLN        "r/as/tln"
#define SETTINGS_KEY_FULL_AS_MXS        "r/as/mxs"
#define SETTINGS_KEY_FULL_LOD        "r/lod"

/* END */

#endif /* SRC_INCLUDE_APP_SETTINGS_APP_SETTINGS_PATHS_H_ */
