/*
 * Copyright (c) 2023 Acme CPU
 *
 *  Created on: 09-May-2023
 *      Author: Rohan Dey (rohan@acmecpu.com)
 */

#ifndef SRC_LIB_LIB_FILE_OPER_LIB_FILE_OPER_CONFIG_H_
#define SRC_LIB_LIB_FILE_OPER_LIB_FILE_OPER_CONFIG_H_

#define LIB_FILE_OPER_MAX_FILES				(CONFIG_LIB_FILE_OPER_MAX_FILES)
#define LIB_FILE_OPER_FILE_PATH_LEN_MAX		(CONFIG_LIB_FILE_OPER_FILE_PATH_LEN_MAX)

#define LIB_THREAD_STACK_SIZE_FILE_OPER		(CONFIG_LIB_THREAD_STACK_SIZE_FILE_OPER)
#define LIB_THREAD_PRIO_FILE_OPER			(CONFIG_LIB_THREAD_PRIO_FILE_OPER)
#define LIB_THREAD_NAME_FILE_OPER			"foper"

#define LIB_FILE_OPER_READ_WHILE_WRITE_CHUNK_SIZE		(100)
#define LIB_FILE_OPER_READ_ONLY_CHUNK_SIZE				(200)

#endif /* SRC_LIB_LIB_FILE_OPER_LIB_FILE_OPER_CONFIG_H_ */
