/*
 * Copyright (c) 2021 Acme CPU
 */

#ifndef SRC_INCLUDE_APP_BLOWER_APP_BLOWER_H_
#define SRC_INCLUDE_APP_BLOWER_APP_BLOWER_H_

#include <stdint.h>
#include "app_settings/app_settings.h"
#include "bsp_blower/bsp_blower.h"
#include "app_storage/app_storage.h"

#define APP_BLOWER_START	BLOWER_ON
#define APP_BLOWER_STOP		BLOWER_OFF

#define PRESS_CMH2O_TO_PA_MUL	(98.0665)
#define PRESS_PA_TO_CMH2O_DIV	(98.0665)
#define PRESS_CMH2O_TO_KPA_MUL	(0.980665)
#define PRESS_KPA_TO_CMH2O_MUL	(10.1972)

/* log file */
#define SENSOR_LOG_DIRECTORY_NAME		CONFIG_APP_BLOWER_SENSOR_LOG_DIR_NAME //"sensor"
#define SENSOR_LOG_DIRECTORY_PATH		APP_STORAGE_MOUNT_POINT_FLASH "/" SENSOR_LOG_DIRECTORY_NAME
#define SENSOR_LOG_CURR_FILE_NAME		CONFIG_APP_BLOWER_SENSOR_LOG_CURR_FILE_NAME //"sensor.dat"
#define SENSOR_LOG_CURR_FILE_PATH		SENSOR_LOG_DIRECTORY_PATH "/" SENSOR_LOG_CURR_FILE_NAME
#define SENSOR_LOG_CURR_FILE_MAX_SIZE_BYTES	(CONFIG_APP_BLOWER_SENSOR_LOG_CURR_FILE_SIZE_MAX_MB * 1000000)
#define SENSOR_LOG_MAX_FILE_COUNT				CONFIG_APP_BLOWER_SENSOR_LOG_MAX_FILE_COUNT

typedef enum {
	APP_BLOWER_OPER_MODE_PID = 0,
	APP_BLOWER_OPER_MODE_TEST,

	APP_BLOWER_OPER_MODE_MAX
} APP_BLOWER_OPER_MODE;

typedef enum {
	APP_BLOWER_SETTINGS_READY=0,
	APP_BLOWER_SETTINGS_BUSY,

	APP_BLOWER_SETTINGS_MAX
} APP_BLOWER_SETTINGS_STATES;

/* struct for enqueing pressure data to be printed */
struct press_data {
	void *fifo_reserved;   	/* 1st word reserved for use by FIFO */
	float data[4];			// contains 4 pressure values
};
struct k_fifo* app_blower_press_fifo_get();

/**/
extern int g_press_csv;

/* Structure to stored all acquired values of the blower */
struct app_blower_params {
	uint32_t acq_volt_mv;		/* acquired blower voltage in mili-volts */
	uint32_t acq_speed_hz;		/* acquired blower speed in hertz */
	int32_t acq_speed_rpm;		/* acquired blower speed in rpm */
	uint16_t faults;			/* blower faults as reported by the bldc driver */
	float acq_pressure_kpa;		/* acquired air pressure generated by blower in Kilo Pascal */
	float controlled_press_kpa;	/* pressure being controlled by PID in Kilo Pascal */
	float acq_air_flow;			/* acquired air flow generated by blower Liters per min */
};

/**
 * @brief Change the operating voltage of the blower
 * @param voltage_mv	operating voltage in mV
 * @return 	0 for success
 * 			-ve for failure
 */
int app_blower_voltage_mv_change(uint32_t voltage_mv);

/**
 * @brief Change the blower speed in rpm
 * @param speed_rpm		speed in rpm (positive number)
 * @return 	0 for success
 * 			-ve for failure
 */
int app_blower_speed_rpm_change(uint32_t speed_rpm);

/**
 * @brief Change the blower PWM duty cycle in percentage
 * @param duty_percent		blower PWM duty cycle in percentage
 * @return 	0 for success
 * 			-ve for failure
 */
int app_blower_duty_percent_change(uint8_t duty_percent);

/**
 * @brief Change the blower run state
 * @param state		APP_BLOWER_START or APP_BLOWER_STOP
 * @return 	0 for success
 * 			-EBUSY if busy, caller must try again
 * 			other -ve value for failure to save settings
 */
int app_blower_settings_change_state(uint8_t state);

//int app_blower_settings_change_all(struct settings_blower *settings);

/**
 * @brief Get the runtime parameters of the blower
 * @param pblw_params[out]		struct app_blower_params object
 * @return 	0 for success
 * 			-ve for failure
 */
int app_blower_runtime_params_get(struct app_blower_params *pblw_params);

/**
 * @brief	Returns the state of the blower, whether running or stopped
 * @return	BLOWER_NOT_RUNNING or BLOWER_RUNNING
 */
uint8_t app_blower_run_state_get();

//int app_blower_state_get(uint8_t *p_blower_state);

/**
 * @brief	Returns the current speed of the blower in RPM
 * @return	0 to max RPM supported by the blower
 * 			-ve if failed to get the RPM
 */
int app_blower_speed_rpm_get(int32_t *speed_rpm);

#if (CONFIG_BLOWER_MOTOR_A101 || CONFIG_BLOWER_MOTOR_A102)
/**
 * @brief	Sends a fault acknowledgment to the motor driver
 * @return	0 for success
 * 			-ve for failure
 */
int app_blower_fault_ack();

/**
 * @brief	Gets the average power from the motor driver
 * @param	power_watts[out]	power returned by the function
 * @return	0 for success
 * 			-ve for failure
 */
int app_blower_power_get(uint16_t *power_avg_w, uint16_t *power_inst_w);
#endif

/**
 * @brief	Sets the PID control loop's set_value.
 * 			This function works only in PID mode
 * @param set_val	The set_value is pressure value in kPa
 */
void app_blower_pid_sv_change(const float set_val);

/**
 * @brief	Sets the PID control loop's actuator constant value
 * 			The actuator constant is a multiplier. It is multiplied with
 * 			the PID algorithm's output to determine the RPM to be changed.
 * 			A greater value means faster response.
 *
 * @param actconst	actuator constant greater than equal to 1
 */
void app_blower_pid_actconst_change(const uint32_t actconst);

/**
 * @brief	Returns the PID control loop's actuator constant value
 * @return	+ve number
 */
uint32_t app_blower_pid_actconst_get();

/**
 * @brief	This function returns the current pressure value in cmH2O which
 * 			is being used in the PID control loop algorithm
 * @return	pressure value in cmH2O
 */
float app_blower_set_press_cmh2o_get();

/**
 * @brief	Sets the operating mode of the app_blower module
 * 			Modes from the enum APP_BLOWER_OPER_MODE are supported
 * @param oper_mode		APP_BLOWER_OPER_MODE values
 * @return	0 for success
 * 			-EINVAL	for incorrect input parameter
 */
int app_blower_oper_mode_set(uint8_t oper_mode);

/**
 * @brief	Gets the current operating mode of the app blower module
 * @return APP_BLOWER_OPER_MODE values
 */
uint8_t app_blower_oper_mode_get();

/**
 * @brief	Sets the blower speed ramp time in ms
 * 			Only works in APP_BLOWER_OPER_MODE_TEST mode
 * 			For APP_BLOWER_OPER_MODE_PID mode the ramp time is adjusted automatically
 * @param ramp_ms		time in ms
 * @return	0 for success
 * 			-1	if trying to set in APP_BLOWER_OPER_MODE_PID mode
 */
int app_blower_ramp_ms_set(uint32_t ramp_ms);

/**
 * @brief	Gets the blower speed ramp time in ms
 * @return ramp time in ms
 */
uint32_t app_blower_ramp_ms_get();

/**
 * @brief	Sets the blower voltage slope calculation data acquisition interval
 * 			Only works in APP_BLOWER_OPER_MODE_PID mode
 * @param vslope_intv_ms		time in ms
 * @return	0 for success
 * 			-1	if trying to set in APP_BLOWER_OPER_MODE_TEST mode
 */
int app_blower_vslope_intv_set(uint32_t vslope_intv_ms);

/**
 * @brief	Gets the blower voltage slope calculation data acquisition interval
 * @return voltage slope interval in ms
 */
uint32_t app_blower_vslope_intv_get();

/**
 * @brief	Sets the blower voltage slope threshold. The PID will adjust the
 * 			ramp time based on this value
 * 			Only works in APP_BLOWER_OPER_MODE_PID mode
 * @param vslope_thres		blower voltage slope threshold
 * @return	0 for success
 * 			-1	if trying to set in APP_BLOWER_OPER_MODE_TEST mode
 */
int app_blower_vslope_thres_set(float vslope_thres);

/**
 * @brief	Gets the blower voltage slope threshold
 * @return blower voltage slope threshold
 */
uint32_t app_blower_vslope_thres_get();

/**
 * @brief	Sets the blower pid kp parameter.
 * @param kp		blower pid parameter kp
 * @return	0 for success
 */
int app_blower_kp_set (float kp);

/**
 * @brief	Sets the blower pid ki parameter.
 * @param ki		blower pid parameter ki
 * @return	0 for success
 */
int app_blower_ki_set (float ki);

/**
 * @brief	Sets the blower pid kd parameter.
 * @param kd		blower pid parameter kd
 * @return	0 for success
 */
int app_blower_kd_set (float kd);

/**
 * @brief	Initializes the app_blower module and starts the PID thread
 * @return	0 for success
 * 			-ve for failure
 */
int app_blower_init();

int app_blower_sample_time_set (float sample_time_ms);
int app_blower_ramp_div_set (int ramp_div);

#endif /* SRC_INCLUDE_APP_BLOWER_APP_BLOWER_H_ */
