################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Src/dac_common_ui.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/motor_power_measurement.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pwm_common.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pwm_curr_fdbk.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Src/r3_f0xx_pwm_curr_fdbk.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/state_machine.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Src/ui_irq_handler.c \
C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c 

OBJS += \
./Middlewares/MotorControl/bus_voltage_sensor.o \
./Middlewares/MotorControl/circle_limitation.o \
./Middlewares/MotorControl/dac_common_ui.o \
./Middlewares/MotorControl/digital_output.o \
./Middlewares/MotorControl/motor_power_measurement.o \
./Middlewares/MotorControl/ntc_temperature_sensor.o \
./Middlewares/MotorControl/open_loop.o \
./Middlewares/MotorControl/pid_regulator.o \
./Middlewares/MotorControl/pqd_motor_power_measurement.o \
./Middlewares/MotorControl/pwm_common.o \
./Middlewares/MotorControl/pwm_curr_fdbk.o \
./Middlewares/MotorControl/r3_f0xx_pwm_curr_fdbk.o \
./Middlewares/MotorControl/r_divider_bus_voltage_sensor.o \
./Middlewares/MotorControl/ramp_ext_mngr.o \
./Middlewares/MotorControl/speed_pos_fdbk.o \
./Middlewares/MotorControl/speed_torq_ctrl.o \
./Middlewares/MotorControl/state_machine.o \
./Middlewares/MotorControl/ui_irq_handler.o \
./Middlewares/MotorControl/virtual_speed_sensor.o 

C_DEPS += \
./Middlewares/MotorControl/bus_voltage_sensor.d \
./Middlewares/MotorControl/circle_limitation.d \
./Middlewares/MotorControl/dac_common_ui.d \
./Middlewares/MotorControl/digital_output.d \
./Middlewares/MotorControl/motor_power_measurement.d \
./Middlewares/MotorControl/ntc_temperature_sensor.d \
./Middlewares/MotorControl/open_loop.d \
./Middlewares/MotorControl/pid_regulator.d \
./Middlewares/MotorControl/pqd_motor_power_measurement.d \
./Middlewares/MotorControl/pwm_common.d \
./Middlewares/MotorControl/pwm_curr_fdbk.d \
./Middlewares/MotorControl/r3_f0xx_pwm_curr_fdbk.d \
./Middlewares/MotorControl/r_divider_bus_voltage_sensor.d \
./Middlewares/MotorControl/ramp_ext_mngr.d \
./Middlewares/MotorControl/speed_pos_fdbk.d \
./Middlewares/MotorControl/speed_torq_ctrl.d \
./Middlewares/MotorControl/state_machine.d \
./Middlewares/MotorControl/ui_irq_handler.d \
./Middlewares/MotorControl/virtual_speed_sensor.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/MotorControl/bus_voltage_sensor.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/bus_voltage_sensor.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/circle_limitation.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/circle_limitation.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/dac_common_ui.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Src/dac_common_ui.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/dac_common_ui.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/digital_output.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/digital_output.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/motor_power_measurement.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/motor_power_measurement.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/motor_power_measurement.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/ntc_temperature_sensor.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/ntc_temperature_sensor.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/open_loop.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/open_loop.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/pid_regulator.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/pid_regulator.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/pqd_motor_power_measurement.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/pqd_motor_power_measurement.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/pwm_common.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pwm_common.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/pwm_common.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/pwm_curr_fdbk.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pwm_curr_fdbk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/pwm_curr_fdbk.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/r3_f0xx_pwm_curr_fdbk.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Src/r3_f0xx_pwm_curr_fdbk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/r3_f0xx_pwm_curr_fdbk.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/r_divider_bus_voltage_sensor.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/r_divider_bus_voltage_sensor.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/ramp_ext_mngr.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/ramp_ext_mngr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/speed_pos_fdbk.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/speed_pos_fdbk.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/speed_torq_ctrl.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/speed_torq_ctrl.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/state_machine.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/state_machine.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/state_machine.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/ui_irq_handler.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Src/ui_irq_handler.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/ui_irq_handler.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/MotorControl/virtual_speed_sensor.o: C:/acmecpu/stm32_workspace/Blower_Driver_STSPIN32F0A/source/Blower_Driver_STSPIN32F0A/MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=gnu11 -DARM_MATH_CM0 -DUSE_HAL_DRIVER -DSTM32F031x6 -c -I../../Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc -I../../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F0xx/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc -I../../MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams -I../../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/MotorControl/virtual_speed_sensor.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

