/*
 * Copyright (c) 2022 Acme CPU
 *
 *  Created on: 29-Dec-2022
 *      Author: Rohan Dey (rohan@acmecpu.cpm)
 */


#ifndef SRC_INCLUDE_APP_PUSH_SWITCH_APP_PUSH_SWITCH_H_
#define SRC_INCLUDE_APP_PUSH_SWITCH_APP_PUSH_SWITCH_H_

// #include <zephyr.h>
#include "lib_push_switch/lib_push_switch.h"

#define APP_MAX_PUSH_SWITCH	    CONFIG_PUSH_SWITCH_MAX_COUNT

#define APP_PUSH_SWITCH_DEVICE_POWER	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_1), gpios))
#define APP_PUSH_SWITCH_DEVICE_CANCEL	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_2), gpios))
#define APP_PUSH_SWITCH_DEVICE_HOME	    DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_3), gpios))
#define APP_PUSH_SWITCH_DEVICE_NO	    DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_4), gpios))
#define APP_PUSH_SWITCH_DEVICE_YES	    DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_5), gpios))
#define APP_PUSH_SWITCH_DEVICE_ENTER	DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_6), gpios))
#define APP_PUSH_SWITCH_DEVICE_MIC		DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_7), gpios))
#define APP_PUSH_SWITCH_DEVICE_SAVE	    DEVICE_DT_GET(DT_GPIO_CTLR(DT_NODELABEL(switch_8), gpios))

// #define APP_PUSH_SWITCH_LABEL_POWER	    DT_GPIO_LABEL(DT_NODELABEL(switch_1), gpios)
// #define APP_PUSH_SWITCH_LABEL_CANCEL	DT_GPIO_LABEL(DT_NODELABEL(switch_2), gpios)
// #define APP_PUSH_SWITCH_LABEL_HOME		DT_GPIO_LABEL(DT_NODELABEL(switch_3), gpios)
// #define APP_PUSH_SWITCH_LABEL_NO	    DT_GPIO_LABEL(DT_NODELABEL(switch_4), gpios)
// #define APP_PUSH_SWITCH_LABEL_YES	    DT_GPIO_LABEL(DT_NODELABEL(switch_5), gpios)
// #define APP_PUSH_SWITCH_LABEL_ENTER	    DT_GPIO_LABEL(DT_NODELABEL(switch_6), gpios)
// #define APP_PUSH_SWITCH_LABEL_MIC		DT_GPIO_LABEL(DT_NODELABEL(switch_7), gpios)
// #define APP_PUSH_SWITCH_LABEL_SAVE		DT_GPIO_LABEL(DT_NODELABEL(switch_8), gpios)

#define APP_PUSH_SWITCH_PIN_POWER		DT_GPIO_PIN(DT_NODELABEL(switch_1), gpios)
#define APP_PUSH_SWITCH_PIN_CANCEL		DT_GPIO_PIN(DT_NODELABEL(switch_2), gpios)
#define APP_PUSH_SWITCH_PIN_HOME		DT_GPIO_PIN(DT_NODELABEL(switch_3), gpios)
#define APP_PUSH_SWITCH_PIN_NO		    DT_GPIO_PIN(DT_NODELABEL(switch_4), gpios)
#define APP_PUSH_SWITCH_PIN_YES		    DT_GPIO_PIN(DT_NODELABEL(switch_5), gpios)
#define APP_PUSH_SWITCH_PIN_ENTER		DT_GPIO_PIN(DT_NODELABEL(switch_6), gpios)
#define APP_PUSH_SWITCH_PIN_MIC		    DT_GPIO_PIN(DT_NODELABEL(switch_7), gpios)
#define APP_PUSH_SWITCH_PIN_SAVE		DT_GPIO_PIN(DT_NODELABEL(switch_8), gpios)

#define APP_PUSH_SWITCH_FLAGS_POWER	    (GPIO_INPUT | GPIO_INT_EDGE_FALLING | DT_GPIO_FLAGS(DT_NODELABEL(switch_1), gpios))
#define APP_PUSH_SWITCH_FLAGS_CANCEL	(GPIO_INPUT | GPIO_INT_LEVEL_LOW | DT_GPIO_FLAGS(DT_NODELABEL(switch_2), gpios))
#define APP_PUSH_SWITCH_FLAGS_HOME		(GPIO_INPUT | GPIO_INT_LEVEL_LOW | DT_GPIO_FLAGS(DT_NODELABEL(switch_3), gpios))
#define APP_PUSH_SWITCH_FLAGS_NO	    (GPIO_INPUT | GPIO_INT_LEVEL_LOW | DT_GPIO_FLAGS(DT_NODELABEL(switch_4), gpios))
#define APP_PUSH_SWITCH_FLAGS_YES	    (GPIO_INPUT | GPIO_INT_LEVEL_LOW | DT_GPIO_FLAGS(DT_NODELABEL(switch_5), gpios))
#define APP_PUSH_SWITCH_FLAGS_ENTER	    (GPIO_INPUT | GPIO_INT_LEVEL_LOW | DT_GPIO_FLAGS(DT_NODELABEL(switch_6), gpios))
#define APP_PUSH_SWITCH_FLAGS_MIC		(GPIO_INPUT | GPIO_INT_LEVEL_LOW | DT_GPIO_FLAGS(DT_NODELABEL(switch_7), gpios))
#define APP_PUSH_SWITCH_FLAGS_SAVE		(GPIO_INPUT | GPIO_INT_LEVEL_LOW | DT_GPIO_FLAGS(DT_NODELABEL(switch_8), gpios))

#define APP_PUSH_SWITCH_MASK_POWER		(1 << APP_PUSH_SWITCH_PIN_POWER)
#define APP_PUSH_SWITCH_MASK_CANCEL	    (1 << APP_PUSH_SWITCH_PIN_CANCEL)
#define APP_PUSH_SWITCH_MASK_HOME		(1 << APP_PUSH_SWITCH_PIN_HOME)
#define APP_PUSH_SWITCH_MASK_NO		    (1 << APP_PUSH_SWITCH_PIN_NO)
#define APP_PUSH_SWITCH_MASK_YES		(1 << APP_PUSH_SWITCH_PIN_YES)
#define APP_PUSH_SWITCH_MASK_ENTER		(1 << APP_PUSH_SWITCH_PIN_ENTER)
#define APP_PUSH_SWITCH_MASK_MIC		(1 << APP_PUSH_SWITCH_PIN_MIC)
#define APP_PUSH_SWITCH_MASK_SAVE		(1 << APP_PUSH_SWITCH_PIN_SAVE)

#define APP_PUSH_SWITCH_MASK_ALL_ASSERTED		(APP_PUSH_SWITCH_MASK_POWER \
												| APP_PUSH_SWITCH_MASK_CANCEL \
												| APP_PUSH_SWITCH_MASK_HOME \
												| APP_PUSH_SWITCH_MASK_NO \
												| APP_PUSH_SWITCH_MASK_YES \
												| APP_PUSH_SWITCH_MASK_ENTER \
												| APP_PUSH_SWITCH_MASK_MIC \
												| APP_PUSH_SWITCH_MASK_SAVE \
)

#define APP_PUSH_SWITCH_PRESS_ACTION_INIT_DATA \
{ \
	{APP_PUSH_SWITCH_DEVICE_POWER, APP_PUSH_SWITCH_MASK_POWER, SWITCH_PRESSED_NORMAL_EDGE, false, 0, APP_PUSH_SWITCH_PIN_POWER},\
	{APP_PUSH_SWITCH_DEVICE_CANCEL, APP_PUSH_SWITCH_MASK_CANCEL, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_CANCEL}, \
    {APP_PUSH_SWITCH_DEVICE_HOME, APP_PUSH_SWITCH_MASK_HOME, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_HOME}, \
	{APP_PUSH_SWITCH_DEVICE_NO, APP_PUSH_SWITCH_MASK_NO, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_NO}, \
	{APP_PUSH_SWITCH_DEVICE_YES, APP_PUSH_SWITCH_MASK_YES, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_YES}, \
	{APP_PUSH_SWITCH_DEVICE_ENTER, APP_PUSH_SWITCH_MASK_ENTER, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_ENTER}, \
	{APP_PUSH_SWITCH_DEVICE_MIC, APP_PUSH_SWITCH_MASK_MIC, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_MIC}, \
	{APP_PUSH_SWITCH_DEVICE_SAVE, APP_PUSH_SWITCH_MASK_SAVE, SWITCH_PRESSED_NORMAL, false, 0, APP_PUSH_SWITCH_PIN_SAVE}, \
}


int app_push_switch_init();

#endif  /*SRC_INCLUDE_APP_PUSH_SWITCH_APP_PUSH_SWITCH_H_*/