/*
 * Copyright (c) 2022 Acme CPU
 *
 *  Created on: 22-Nov-2022
 *      Author: Rohan Dey (rohan@acmecpu.cpm)
 */

#ifndef MODULES_SHMAX30101_SHMAX30101_H_
#define MODULES_SHMAX30101_SHMAX30101_H_

#include <stdint.h>
#include <zephyr/drivers/sensor.h>

enum sensor_attribute_shmax30101 {
    SENSOR_ATTR_WHRM_HR = SENSOR_ATTR_PRIV_START + 11,
    SENSOR_ATTR_WHRM_SPO2,
    SENSOR_ATTR_WHRM_STATUS,

    SENSOR_ATTR_GET_FORMAT_PPG_0,
	SENSOR_ATTR_GET_FORMAT_BPT_0,
	SENSOR_ATTR_GET_FORMAT_BPT_1,
	SENSOR_ATTR_READ_PPG_0,
	SENSOR_ATTR_READ_BPT_0,
	SENSOR_ATTR_READ_BPT_1,
	SENSOR_ATTR_GET_REG_PPG,
	SENSOR_ATTR_SET_REG_PPG,
	SENSOR_ATTR_DUMP_REG_PPG,
	SENSOR_ATTR_SET_AGC_DIS,
	SENSOR_ATTR_SET_AGC_EN,
	SENSOR_ATTR_SET_CFG_BPT_MED,
	SENSOR_ATTR_SET_CFG_BPT_SYS_BP,
	SENSOR_ATTR_SET_CFG_BPT_DIA_BP,
	SENSOR_ATTR_SET_CFG_BPT_DATE,
	SENSOR_ATTR_SET_CFG_BPT_NONREST,
	SENSOR_ATTR_SET_CFG_SPO2_CAL,
	SENSOR_ATTR_SELF_TEST_PPG_OS24,
	SENSOR_ATTR_SELF_TEST_PPG_ACC,
	SENSOR_ATTR_STOP_PPG_0,
};

enum sensor_channel_shmax30101 {
	SENSOR_CHAN_HEART_RATE = SENSOR_CHAN_PRIV_START + 11,
	SENSOR_CHAN_SPO2,
	SENSOR_CHAN_HR_AND_SPO2,
};

#endif /*MODULES_SHMAX30101_SHMAX30101_H_*/