# Copyright (c) 2022 Acme CPU

#-------------------------------------------------------------- ARM specific configs
CONFIG_FPU=y

#-------------------------------------------------------------- Main thread
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_NO_YIELD=y
CONFIG_HEAP_MEM_POOL_SIZE=30720
#CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE=30720
CONFIG_MEM_SLAB_TRACE_MAX_UTILIZATION=y

#-------------------------------------------------------------- System monitoring - Thread analyzer configs
#CONFIG_THREAD_ANALYZER=y
#CONFIG_THREAD_ANALYZER_USE_LOG=y
#CONFIG_THREAD_ANALYZER_USE_PRINTK=y
#CONFIG_THREAD_ANALYZER_AUTO=y
#CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=30

#-------------------------------------------------------------- Compiler configurations
CONFIG_NEWLIB_LIBC=y
#CONFIG_NEWLIB_LIBC_NANO=n
#CONFIG_HAS_NEWLIB_LIBC_NANO=n
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_CBPRINTF_FP_SUPPORT=y

