/*
 * Copyright (c) 2022 Acme CPU
 *
 *  Created on: 12-Dec-2022
 *      Author: Rohan Dey (rohan@acmecpu.cpm)
 */

#ifndef SRC_INCLUDE_APP_BATTERY_APP_BATTERY_H_
#define SRC_INCLUDE_APP_BATTERY_APP_BATTERY_H_

#include <stdint.h>
#if (CONFIG_BQ25611D)
#include "bq25611d.h"
#endif

#define APP_BATTERY_CHARGE_CURRENT_MAX          CONFIG_APP_BATTERY_CHARGE_CURRENT_MAX
#define APP_BATTERY_CHARGER_INPUT_CURRENT_MAX   CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_MAX

#define APP_BATTERY_CHARGE_CURR_LIMIT_50		50			/* charge current limit = 50 MA */
#define APP_BATTERY_CHARGE_CURR_LIMIT_100		100			/* charge current limit = 100 MA */
#define APP_BATTERY_CHARGE_CURR_LIMIT_250		250			/* charge current limit = 250 MA */
#define APP_BATTERY_CHARGE_CURR_LIMIT_500		500			/* charge current limit = 500 MA */
#define APP_BATTERY_CHARGE_CURR_LIMIT_1000		1000		/* charge current limit = 1000 MA */
#define APP_BATTERY_CHARGE_CURR_LIMIT_1500		1500		/* charge current limit = 1500 MA */
#define APP_BATTERY_CHARGE_CURR_LIMIT_2000		2000		/* charge current limit = 2000 MA */
#define APP_BATTERY_CHARGE_CURR_LIMIT_3000		3000		/* charge current limit = 3000 MA */
#define APP_BATTERY_CHARGE_CURR_LIMIT_5000		5000		/* charge current limit = 5000 MA */

/* Charger input current limits */
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_100      100
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_200      200
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_400      400
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_500      500
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_800      800
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_1000     1000
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_1500     1500
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_2000     2000
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_2500     2500
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_3000     3000
#define APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_5000     5000

/**
 * Battery charger current limit settings for driver
 * */
#if (CONFIG_BQ25611D)

#if (CONFIG_APP_BATTERY_CHARGE_CURRENT_LIMIT == APP_BATTERY_CHARGE_CURR_LIMIT_50)
#define APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS	(BQ25611D_CHARGE_CURRENT_LIMIT_60MA)				/* assigning the nearest value of 60MA which is supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGE_CURRENT_LIMIT == APP_BATTERY_CHARGE_CURR_LIMIT_100)
#define APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS	(BQ25611D_CHARGE_CURRENT_LIMIT_120MA)				/* assigning the nearest value of 120MA which is supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGE_CURRENT_LIMIT == APP_BATTERY_CHARGE_CURR_LIMIT_250)
#define APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS	(BQ25611D_CHARGE_CURRENT_LIMIT_240MA)				/* assigning the nearest value of 240MA which is supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGE_CURRENT_LIMIT == APP_BATTERY_CHARGE_CURR_LIMIT_500)
#define APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS	(BQ25611D_CHARGE_CURRENT_LIMIT_480MA)				/* assigning the nearest value of 480MA which is supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGE_CURRENT_LIMIT == APP_BATTERY_CHARGE_CURR_LIMIT_1000)
#define APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS	(BQ25611D_CHARGE_CURRENT_LIMIT_960MA | BQ25611D_CHARGE_CURRENT_LIMIT_60MA)		/* assigning the nearest value of 1020MA which is supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGE_CURRENT_LIMIT == APP_BATTERY_CHARGE_CURR_LIMIT_2000)
#define APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS	(BQ25611D_CHARGE_CURRENT_LIMIT_1920MA | BQ25611D_CHARGE_CURRENT_LIMIT_120MA)	/* assigning the nearest value of 2040MA which is supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGE_CURRENT_LIMIT == APP_BATTERY_CHARGE_CURR_LIMIT_3000)
#define APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS	(BQ25611D_CHARGE_CURRENT_LIMIT_1920MA | BQ25611D_CHARGE_CURRENT_LIMIT_960MA | BQ25611D_CHARGE_CURRENT_LIMIT_120MA)

//#elif (CONFIG_APP_BATTERY_CHARGE_CURRENT_LIMIT == APP_BATTERY_CHARGE_CURR_LIMIT_5000)
#else
/* assigning the maximum value supported by the driver */
#define APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS	(BQ25611D_CHARGE_CURRENT_LIMIT_1920MA | BQ25611D_CHARGE_CURRENT_LIMIT_960MA | BQ25611D_CHARGE_CURRENT_LIMIT_120MA)
#endif  /* APP_BATTERY_CHARGE_CURR_LIMIT_SETTINGS */

/* Note: for input current limit there is a 100mA offset hence all values set are having 100mA less */
#if (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_100)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(0)    /* assigning the nearest value supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_200)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_100MA)    /* assigning the nearest value supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_400)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_100MA | BQ25611D_INPUT_CURRENT_LIMIT_200MA)    /* assigning the nearest value supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_500)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_400MA)    /* assigning the nearest value supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_800)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_100MA | BQ25611D_INPUT_CURRENT_LIMIT_200MA | BQ25611D_INPUT_CURRENT_LIMIT_400MA)    /* assigning the nearest value supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_1000)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_100MA | BQ25611D_INPUT_CURRENT_LIMIT_800MA)    /* assigning the nearest value supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_2000)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_100MA | BQ25611D_INPUT_CURRENT_LIMIT_200MA | BQ25611D_INPUT_CURRENT_LIMIT_1600MA)    /* assigning the nearest value supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_2500)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_800MA | BQ25611D_INPUT_CURRENT_LIMIT_1600MA)    /* assigning the nearest value supported by the driver */

#elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_3000)
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_100MA | BQ25611D_INPUT_CURRENT_LIMIT_400MA | BQ25611D_INPUT_CURRENT_LIMIT_800MA | BQ25611D_INPUT_CURRENT_LIMIT_1600MA)    /* assigning the nearest value supported by the driver */

// #elif (CONFIG_APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT == APP_BATTERY_CHARGE_INPUT_CURRENT_LIMIT_5000)
#else
/* assigning the maximum value supported by the driver */
#define APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS	(BQ25611D_INPUT_CURRENT_LIMIT_100MA | BQ25611D_INPUT_CURRENT_LIMIT_200MA | BQ25611D_INPUT_CURRENT_LIMIT_400MA | BQ25611D_INPUT_CURRENT_LIMIT_800MA | BQ25611D_INPUT_CURRENT_LIMIT_1600MA)    /* assigning the nearest value supported by the driver */

#endif  /* APP_BATTERY_CHARGER_INPUT_CURRENT_LIMIT_SETTINGS */
#endif /* CONFIG_BQ25611D */

typedef enum {
	APP_BATT_NOT_CHARGING=0,
	APP_BATT_CHARGING,
	APP_BATT_UNKNOWN
} APP_BATTERY_CHARGING_STATUS;

typedef enum {
	APP_BATT_CHRG_EVENT_ADAPTER_ATTACHED=0,
	APP_BATT_CHRG_EVENT_ADAPTER_REMOVED,
	APP_BATT_CHRG_EVENT_CHARGE_COMPLETE,
	APP_BATT_CHRG_EVENT_FAULT,
} APP_BATTERY_CHARGER_EVENTS;


typedef void (*app_battery_cb_handler_t)(APP_BATTERY_CHARGER_EVENTS event);

int app_battery_FG_level_get(uint8_t *batt_level);

int app_battery_FG_charge_complete_set();

int app_battery_FG_accumulated_charge_set(uint32_t charge_mah);

int app_battery_register_cb(app_battery_cb_handler_t handler);

int app_battery_current_limits_set(uint32_t chg_cur_lim, uint32_t in_cur_lim);

int app_battery_charging_status_get(uint8_t *charging_status,
                                    uint32_t *charge_curr_ma, 
                                    uint8_t *source_type,
                                    uint32_t *in_curr_lim);

int app_battery_schedule_system_off(uint32_t *ms_to_off);

int app_battery_mvolts_get(uint32_t *batt_mvolts);

int app_battery_available_capacity_get(float *batt_capacity);

int app_battery_init();


#endif /*SRC_INCLUDE_APP_BATTERY_APP_BATTERY_H_*/