/*
 * Copyright (c) 2021 Acme CPU
 */



#ifndef SRC_BSP_BSP_MEMBRANE_SWITCH_BSP_MEMBRANE_SWITCH_PRIV_H_
#define SRC_BSP_BSP_MEMBRANE_SWITCH_BSP_MEMBRANE_SWITCH_PRIV_H_

#include <zephyr.h>
#include <kernel.h>
#include "bsp_membrane_switch/bsp_membrane_switch.h"

struct press_action_property {
	uint32_t asserted_switch;
	BSP_MEMBR_SWITCH_PRESSED_TYPE press_type;
	bool detection_continue;
	int64_t pressed_start;
	const char* asserted_switch_label;
	int asserted_switch_pin;
	struct k_work interrupt_worker;
};


#if CONFIG_BOARD_C204_CORE
#define BSP_MEMBR_SWITCH_MASK_ALL_ASSERTED		(BSP_MEMBR_SWITCH_MASK_ENTER \
												| BSP_MEMBR_SWITCH_MASK_BACK \
												| BSP_MEMBR_SWITCH_MASK_LEFT \
												| BSP_MEMBR_SWITCH_MASK_POWER \
												| BSP_MEMBR_SWITCH_MASK_RIGHT \
												| BSP_MEMBR_SWITCH_MASK_DOWN \
												| BSP_MEMBR_SWITCH_MASK_UP \
												| BSP_MEMBR_SWITCH_MASK_HOME \
)

#define BSP_MEMBR_PRESS_ACTION_INIT_DATA \
{ \
	{BSP_MEMBR_SWITCH_MASK_ENTER, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_ENTER, BSP_MEMBR_SWITCH_PIN_ENTER},\
	{BSP_MEMBR_SWITCH_MASK_BACK, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_BACK, BSP_MEMBR_SWITCH_PIN_BACK}, \
	{BSP_MEMBR_SWITCH_MASK_LEFT, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_LEFT, BSP_MEMBR_SWITCH_PIN_LEFT}, \
	{BSP_MEMBR_SWITCH_MASK_POWER, SWITCH_PRESSED_NORMAL_EDGE_LONG, false, 0, BSP_MEMBR_SWITCH_LABEL_POWER, BSP_MEMBR_SWITCH_PIN_POWER}, \
	{BSP_MEMBR_SWITCH_MASK_RIGHT, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_RIGHT, BSP_MEMBR_SWITCH_PIN_RIGHT}, \
	{BSP_MEMBR_SWITCH_MASK_DOWN, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_DOWN, BSP_MEMBR_SWITCH_PIN_DOWN}, \
	{BSP_MEMBR_SWITCH_MASK_UP, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_UP, BSP_MEMBR_SWITCH_PIN_UP}, \
	{BSP_MEMBR_SWITCH_MASK_HOME, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_HOME, BSP_MEMBR_SWITCH_PIN_HOME}, \
}
#else
#define BSP_MEMBR_SWITCH_MASK_ALL_ASSERTED		(BSP_MEMBR_SWITCH_MASK_CHECK \
												| BSP_MEMBR_SWITCH_MASK_BACK \
												| BSP_MEMBR_SWITCH_MASK_LEFT \
												| BSP_MEMBR_SWITCH_MASK_RIGHT \
												| BSP_MEMBR_SWITCH_MASK_UP \
												| BSP_MEMBR_SWITCH_MASK_DOWN \
												| BSP_MEMBR_SWITCH_MASK_POWER)

#define BSP_MEMBR_PRESS_ACTION_INIT_DATA \
{ \
	{BSP_MEMBR_SWITCH_MASK_CHECK, SWITCH_PRESSED_NORMAL_EDGE_LONG, false, 0, BSP_MEMBR_SWITCH_LABEL_CHECK, BSP_MEMBR_SWITCH_PIN_CHECK},\
	{BSP_MEMBR_SWITCH_MASK_BACK, SWITCH_PRESSED_NORMAL_EDGE_LONG, false, 0, BSP_MEMBR_SWITCH_LABEL_BACK, BSP_MEMBR_SWITCH_PIN_BACK}, \
	{BSP_MEMBR_SWITCH_MASK_LEFT, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_LEFT, BSP_MEMBR_SWITCH_PIN_LEFT}, \
	{BSP_MEMBR_SWITCH_MASK_RIGHT, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_RIGHT, BSP_MEMBR_SWITCH_PIN_RIGHT}, \
	{BSP_MEMBR_SWITCH_MASK_UP, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_UP, BSP_MEMBR_SWITCH_PIN_UP}, \
	{BSP_MEMBR_SWITCH_MASK_DOWN, SWITCH_PRESSED_NORMAL, false, 0, BSP_MEMBR_SWITCH_LABEL_DOWN, BSP_MEMBR_SWITCH_PIN_DOWN}, \
	{BSP_MEMBR_SWITCH_MASK_POWER, SWITCH_PRESSED_NORMAL_EDGE_LONG, false, 0, BSP_MEMBR_SWITCH_LABEL_POWER, BSP_MEMBR_SWITCH_PIN_POWER}, \
}
#endif	/* CONFIG_BOARD_C204_CORE */

#endif /* SRC_BSP_BSP_MEMBRANE_SWITCH_BSP_MEMBRANE_SWITCH_PRIV_H_ */
