/*
 * lib_stm32bl_host_config.h
 *
 *  Created on: 25-Jul-2023
 *      Author: Rohan Dey (rohan@acmecpu.com)
 */

#ifndef SRC_LIB_LIB_STM32BL_HOST_LIB_STM32BL_HOST_CONFIG_H_
#define SRC_LIB_LIB_STM32BL_HOST_LIB_STM32BL_HOST_CONFIG_H_

#define DEBUG_LOG			1
#define PLATFORM_ESP_IDF	0
#define PLATFORM_ZEPHYR		1

#define STM32BLH_CONFIG_STM32_APP_START_ADDR	{0x08, 0x00, 0x00, 0x00}	//0x08000000 //CONFIG_STM32_APP_START_ADDR

#define STM32BLH_CONFIG_USART_BAUD			115200
#define STM32BLH_CONFIG_USART_DATABITS		8
#define STM32BLH_CONFIG_USART_PARITY		UART_PARITY_EVEN
#define STM32BLH_CONFIG_USART_STOPBITS		1
#define STM32BLH_CONFIG_USART_HWFLOWCTRL	0

#endif /* SRC_LIB_LIB_STM32BL_HOST_LIB_STM32BL_HOST_CONFIG_H_ */
