/*
 * Copyright (c) 2021 Acme CPU
 *
 *  Created on: 28-Mar-2023
 *      Author: Rohan Dey (rohan@acmecpu.com)
 */

#include "app_settings/app_settings_data.h"
#include "app_net/app_net_html_gen.h"

struct html_menu_data g_html_menu[SETTINGS_COUNT_MAX] =
{
		/********************************************************************
		 * The below lines are generated by codegen.
		 * Do not edit them! The sequence must be maintained
		 *********************************************************************/

		{&g_sdata[0], -1},        //0
                {&g_sdata[1], -1},        //1
                {&g_sdata[2], -1},        //2
                {&g_sdata[3], -1},        //3
                {&g_sdata[4], -1},        //4
                {&g_sdata[5], -1},        //5
                {&g_sdata[6], -1},        //6
                {&g_sdata[7], -1},        //7
                {&g_sdata[8], -1},        //8
                {&g_sdata[9], -1},        //9
                {&g_sdata[10], -1},        //10
                {&g_sdata[11], -1},        //11
                {&g_sdata[12], -1},        //12
                {&g_sdata[13], -1},        //13
                {&g_sdata[14], -1},        //14
                {&g_sdata[15], -1},        //15
                {&g_sdata[16], -1},        //16
                {&g_sdata[17], -1},        //17
                {&g_sdata[18], -1},        //18
                {&g_sdata[19], -1},        //19
                {&g_sdata[20], -1},        //20
                {&g_sdata[21], -1},        //21
                {&g_sdata[22], -1},        //22
                {&g_sdata[23], -1},        //23
                {&g_sdata[24], -1},        //24
                {&g_sdata[25], -1},        //25
                {&g_sdata[26], -1},        //26
                {&g_sdata[27], -1},        //27
                {&g_sdata[28], -1},        //28
                {&g_sdata[29], -1},        //29
                {&g_sdata[30], -1},        //30
                {&g_sdata[31], -1},        //31
                {&g_sdata[32], -1},        //32
                {&g_sdata[33], -1},        //33
                {&g_sdata[34], -1},        //34
                {&g_sdata[35], -1},        //35
                {&g_sdata[36], -1},        //36
                {&g_sdata[37], -1},        //37
                {&g_sdata[38], -1},        //38
                {&g_sdata[39], -1},        //39
                {&g_sdata[40], -1},        //40
                {&g_sdata[41], -1},        //41
                {&g_sdata[42], -1},        //42
                {&g_sdata[43], -1},        //43
                {&g_sdata[44], -1},        //44
                {&g_sdata[45], -1},        //45
                {&g_sdata[46], -1},        //46
                {&g_sdata[47], -1},        //47
                {&g_sdata[48], -1},        //48
                {&g_sdata[49], -1},        //49
                {&g_sdata[50], -1},        //50
                {&g_sdata[51], -1},        //51
                {&g_sdata[52], -1},        //52
                {&g_sdata[53], -1},        //53
                {&g_sdata[54], -1},        //54
                {&g_sdata[55], -1},        //55
                {&g_sdata[56], -1},        //56
                {&g_sdata[57], -1},        //57
                {&g_sdata[58], -1},        //58
                {&g_sdata[59], -1},        //59
                {&g_sdata[60], -1},        //60
                {&g_sdata[61], -1},        //61
                {&g_sdata[62], -1},        //62
                {&g_sdata[63], -1},        //63
                {&g_sdata[64], -1},        //64
                {&g_sdata[65], -1},        //65
                {&g_sdata[66], -1},        //66
                {&g_sdata[67], -1},        //67
                {&g_sdata[68], -1},        //68
                {&g_sdata[69], -1},        //69
                {&g_sdata[70], -1},        //70
                {&g_sdata[71], -1},        //71
                {&g_sdata[72], -1},        //72
                {&g_sdata[73], -1},        //73
                {&g_sdata[74], -1},        //74
                {&g_sdata[75], -1},        //75
                {&g_sdata[76], -1},        //76
                {&g_sdata[77], -1},        //77
                {&g_sdata[78], -1},        //78

		/* end */
};
