/*
 * Copyright (c) 2023 Acme CPU
 *
 *  Created on: 20-Mar-2023
 *      Author: Rohan Dey (rohan@acmecpu.com)
 */


#include "app_display/app_display_menu.h"
#include "app_settings/app_settings_data.h"
#include "app_settings/app_settings_value.h"
#include "app_display/c20x_screens/c20x_screen_settings_extra_func.h"

//static struct gui_param_metadata m_gui_mdata[SETTINGS_COUNT_MAX];

/********************************************************************
 * GUI DATA
 *********************************************************************/
/* Gui data - developer settings */
static struct gui_param_metadata gpm_BlowerMode = {.options = &g_mdata_BlowerMode};
static struct gui_param_metadata gpm_devUSB = {.options = &g_mdata_devUSB};
static struct gui_param_metadata gpm_reloadSettings = {.options = &g_mdata_reloadSettings};

/* Gui data - Tech settings */
static struct gui_param_metadata gpm_CPAP = {.options = &g_mdata_CPAP};
static struct gui_param_metadata gpm_Mode = {.options = &g_mdata_Mode};

/* Gui data - device settings */
static struct gui_param_metadata gpm_WiFi = {.options = &g_mdata_WiFi};
static struct gui_param_metadata gpm_WiFiSSID = {.options = &g_mdata_SSID};
static struct gui_param_metadata gpm_WiFiPwd;
static struct gui_param_metadata gpm_WiFiAP = {.options = &g_mdata_WiFiAP};
static struct gui_param_metadata gpm_lang = {.options = &g_mdata_lang};
static struct gui_param_metadata gpm_EraseData = {.options = &g_mdata_EraseData};
static struct gui_param_metadata gpm_ptAccExt = {.options = &g_mdata_ptAccExt};
static struct gui_param_metadata gpm_Freset = {.options = &g_mdata_Freset};
static struct gui_param_metadata gpm_Time[2] =
{
		{.options = &g_mdata_Time[0]},
		{.options = &g_mdata_Time[1]},
//		{.options = &g_mdata_Time[2]}
};
static struct gui_param_metadata gpm_Date[3] =
{
		{.options = &g_mdata_Date[0]},
		{.options = &g_mdata_Date[1]},
		{.options = &g_mdata_Date[2]}
};

/* Gui data - comfort settings */
static struct gui_param_metadata gpm_LeakAlert = {.options = &g_mdata_LeakAlert};
static struct gui_param_metadata gpm_AutoOff = {.options = &g_mdata_AutoOff};
static struct gui_param_metadata gpm_AutoOn = {.options = &g_mdata_AutoOn};
static struct gui_param_metadata gpm_SettleTime = {.options = &g_mdata_SettleTime};
static struct gui_param_metadata gpm_RampTime = {.options = &g_mdata_RampTime};
static struct gui_param_metadata gpm_Humidity = {.options = &g_mdata_Humidity};
static struct gui_param_metadata gpm_HeaterState = {.options = &g_mdata_HeaterState};
static struct gui_param_metadata gpm_Temp = {.options = &g_mdata_Temp};
static struct gui_param_metadata gpm_PlaceOfUse = {.options = &g_mdata_PlaceOfUse};
static struct gui_param_metadata gpm_SensorLocation = {.options = &g_mdata_SensorLocation};

/* Gui data - advanced tech settings */
static struct gui_param_metadata gpm_Trigger = {.options = &g_mdata_Trigger};
static struct gui_param_metadata gpm_BatteryStatus = {.options = &g_mdata_BatteryStatus};
static struct gui_param_metadata gpm_Cycle = {.options = &g_mdata_Cycle};
static struct gui_param_metadata gpm_TubeLength = {.options = &g_mdata_TubeLength};
static struct gui_param_metadata gpm_MaxSettle = {.options = &g_mdata_MaxSettle};

/* Gui data - blower */
static struct gui_param_metadata gpm_BlwState = {.options = &g_mdata_BlwState};

const struct app_display_menu g_display_menu[SETTINGS_COUNT_MAX] =
{
		/********************************************************************
		 * The below lines are generated by codegen.
		 * Do not edit them! The sequence must be maintained
		 *********************************************************************/

		{&g_sdata[0], NULL, GUI_OBJ_LABEL, NULL},        //0
                {&g_sdata[1], &gpm_BlwState, GUI_OBJ_ROLLER, NULL},        //1
                {&g_sdata[2], NULL, GUI_OBJ_NONE, NULL},        //2
                {&g_sdata[3], &gpm_BlowerMode, GUI_OBJ_ROLLER, NULL},        //3
                {&g_sdata[4], NULL, GUI_OBJ_TEXTBOX, NULL},        //4
                {&g_sdata[5], NULL, GUI_OBJ_TEXTBOX, NULL},        //5
                {&g_sdata[6], &gpm_devUSB, GUI_OBJ_ROLLER, NULL},        //6
                {&g_sdata[7], NULL, GUI_OBJ_NONE, NULL},        //7
                {&g_sdata[8], &gpm_Mode, GUI_OBJ_ROLLER, NULL},        //8
                {&g_sdata[9], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //9
                {&g_sdata[10], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //10
                {&g_sdata[11], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //11
                {&g_sdata[12], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //12
                {&g_sdata[13], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //13
                {&g_sdata[14], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //14
                {&g_sdata[15], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //15
                {&g_sdata[16], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //16
                {&g_sdata[17], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //17
                {&g_sdata[18], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //18
                {&g_sdata[19], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //19
                {&g_sdata[20], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //20
                {&g_sdata[21], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //21
                {&g_sdata[22], &gpm_CPAP, GUI_OBJ_ROLLER, NULL},        //22
                {&g_sdata[23], NULL, GUI_OBJ_NONE, NULL},        //23
                {&g_sdata[24], NULL, GUI_OBJ_LABEL, NULL},        //24
                {&g_sdata[25], gpm_Date, GUI_OBJ_ROLLER, NULL},        //25
                {&g_sdata[26], NULL, GUI_OBJ_NONE, NULL},        //26
                {&g_sdata[27], NULL, GUI_OBJ_NONE, NULL},        //27
                {&g_sdata[28], NULL, GUI_OBJ_NONE, NULL},        //28
                {&g_sdata[29], gpm_Time, GUI_OBJ_ROLLER, NULL},        //29
                {&g_sdata[30], NULL, GUI_OBJ_NONE, NULL},        //30
                {&g_sdata[31], NULL, GUI_OBJ_NONE, NULL},        //31
                {&g_sdata[32], &gpm_Freset, GUI_OBJ_ROLLER, NULL},        //32
                {&g_sdata[33], &gpm_ptAccExt, GUI_OBJ_ROLLER, NULL},        //33
                {&g_sdata[34], &gpm_EraseData, GUI_OBJ_ROLLER, NULL},        //34
                {&g_sdata[35], &gpm_lang, GUI_OBJ_ROLLER, NULL},        //35
                {&g_sdata[36], NULL, GUI_OBJ_NONE, NULL},        //36
                {&g_sdata[37], &gpm_WiFiAP, GUI_OBJ_ROLLER, settings_hotspot_extra_func},        //37
                {&g_sdata[38], &gpm_WiFiPwd, GUI_OBJ_TEXTBOX, NULL},        //38
                {&g_sdata[39], NULL, GUI_OBJ_NONE, NULL},        //39
                {&g_sdata[40], NULL, GUI_OBJ_LABEL, NULL},        //40
                {&g_sdata[41], NULL, GUI_OBJ_LABEL, NULL},        //41
                {&g_sdata[42], &gpm_WiFiSSID, GUI_OBJ_ROLLER, NULL},        //42
                {&g_sdata[43], NULL, GUI_OBJ_LABEL, NULL},        //43
                {&g_sdata[44], &gpm_WiFi, GUI_OBJ_ROLLER, NULL},        //44
                {&g_sdata[45], NULL, GUI_OBJ_NONE, NULL},        //45
                {&g_sdata[46], &gpm_PlaceOfUse, GUI_OBJ_ROLLER, NULL},        //46
                {&g_sdata[47], &gpm_Humidity, GUI_OBJ_ROLLER, NULL},        //47
                {&g_sdata[48], &gpm_RampTime, GUI_OBJ_ROLLER, NULL},        //48
                {&g_sdata[49], &gpm_SettleTime, GUI_OBJ_ROLLER, NULL},        //49
                {&g_sdata[50], &gpm_AutoOn, GUI_OBJ_ROLLER, NULL},        //50
                {&g_sdata[51], &gpm_AutoOff, GUI_OBJ_ROLLER, NULL},        //51
                {&g_sdata[52], &gpm_LeakAlert, GUI_OBJ_ROLLER, NULL},        //52
                {&g_sdata[53], NULL, GUI_OBJ_NONE, NULL},        //53
                {&g_sdata[54], NULL, GUI_OBJ_NONE, NULL},        //54
                {&g_sdata[55], &gpm_HeaterState, GUI_OBJ_ROLLER, NULL},        //55
                {&g_sdata[56], &gpm_Humidity, GUI_OBJ_ROLLER, NULL},        //56
                {&g_sdata[57], NULL, GUI_OBJ_NONE, NULL},        //57
                {&g_sdata[58], &gpm_HeaterState, GUI_OBJ_ROLLER, NULL},        //58
                {&g_sdata[59], &gpm_Temp, GUI_OBJ_ROLLER, NULL},        //59
                {&g_sdata[60], NULL, GUI_OBJ_NONE, NULL},        //60
                {&g_sdata[61], NULL, GUI_OBJ_NONE, NULL},        //61
                {&g_sdata[62], &gpm_SensorLocation, GUI_OBJ_ROLLER, NULL},        //62
                {&g_sdata[63], &gpm_SensorLocation, GUI_OBJ_ROLLER, NULL},        //63
                {&g_sdata[64], &gpm_SensorLocation, GUI_OBJ_ROLLER, NULL},        //64
                {&g_sdata[65], &gpm_SensorLocation, GUI_OBJ_ROLLER, NULL},        //65
                {&g_sdata[66], &gpm_SensorLocation, GUI_OBJ_ROLLER, NULL},        //66
                {&g_sdata[67], NULL, GUI_OBJ_NONE, NULL},        //67
                {&g_sdata[68], &gpm_SensorLocation, GUI_OBJ_ROLLER, NULL},        //68
                {&g_sdata[69], NULL, GUI_OBJ_NONE, NULL},        //69
                {&g_sdata[70], &gpm_SensorLocation, GUI_OBJ_ROLLER, NULL},        //70
                {&g_sdata[71], NULL, GUI_OBJ_NONE, NULL},        //71
                {&g_sdata[72], &gpm_LeakAlert, GUI_OBJ_ROLLER, NULL},        //72
                {&g_sdata[73], &gpm_BatteryStatus, GUI_OBJ_ROLLER, NULL},        //73
                {&g_sdata[74], &gpm_Trigger, GUI_OBJ_ROLLER, NULL},        //74
                {&g_sdata[75], &gpm_Cycle, GUI_OBJ_ROLLER, NULL},        //75
                {&g_sdata[76], &gpm_TubeLength, GUI_OBJ_ROLLER, NULL},        //76
                {&g_sdata[77], &gpm_MaxSettle, GUI_OBJ_ROLLER, NULL},        //77
                {&g_sdata[78], &gpm_reloadSettings, GUI_OBJ_ROLLER, NULL},        //78

		/* end */
};

void app_display_menu_init()
{
//	for (int i=0; i<SETTINGS_COUNT_MAX; i++) {
//		if (g_display_menu[i].gui_data) {
//			g_display_menu[i].gui_data->options = g_sdata[i].options;
//		}
//		m_gui_mdata[i].options = g_sdata[i].options;
//	}
}

