/*
 * Copyright (c) 2021 Acme CPU
 *
 *  Created on: 30-Nov-2021
 *      Author: Rohan Dey (rohan@acmecpu.com)
 */

#include <stddef.h>
#include <stdbool.h>
#include "app_settings/app_settings_value.h"
#include "app_settings/app_settings_display_data.h"
#include "app_display/c20x_screens/c20x_screen_settings_extra_func.h"





/********************************************************************
 * Menu display data
 *********************************************************************/
const struct settings_display_item g_display_item[SETTINGS_COUNT_MAX] =
{
#if 0
		/* */
		{SETTINGS_KEY_FULL_LOAD, "Load", false, SETTING_DATATYPE_NONE, SETTING_LVOBJ_NONE},
		{SETTINGS_KEY_FULL_LOAD_SET, "Load", false, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SWITCH},						// 2

		/* Log and Data */
		{SETTINGS_KEY_FULL_LOG, "Logs", true, SETTING_DATATYPE_NONE, SETTING_LVOBJ_NONE},
		{SETTINGS_KEY_FULL_LOG_STORE, "Save Logs", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SWITCH},
#if (SETTINGS_NEEDED)
		{SETTINGS_KEY_FULL_LOG_TX_DUR, "Upload Log Interval", false, SETTING_DATATYPE_UINT32, SETTING_LVOBJ_SPINBOX},
		{SETTINGS_KEY_FULL_LOG_TX_MED, "Upload Log Via", false, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_ROLLER},
#endif
		{SETTINGS_KEY_FULL_DATA_STORE, "Save Data", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SWITCH},				// 5
#if (SETTINGS_NEEDED)
		{SETTINGS_KEY_FULL_DATA_TX_DUR, "Upload Data Interval", false, SETTING_DATATYPE_UINT32, SETTING_LVOBJ_SPINBOX},
		{SETTINGS_KEY_FULL_DATA_TX_MED, "Upload Data Via", false, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_ROLLER},
#endif

		/* Power and Charging */
		{SETTINGS_KEY_FULL_POWER_CHRG, "Pwr St", true, SETTING_DATATYPE_NONE, SETTING_LVOBJ_NONE},
		{SETTINGS_KEY_FULL_POWERED_ON, "Pwr On St", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_ROLLER},
		{SETTINGS_KEY_FULL_POWERED_OFF, "Pwr Off St", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_ROLLER},
		{SETTINGS_KEY_FULL_CHRG_DEV_ON, "Charger when On", false, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_ROLLER},
		{SETTINGS_KEY_FULL_CHRG_DEV_OFF, "Charger when Off", false, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_ROLLER},			// 10

#if (SETTINGS_NEEDED)
		/* Prescription */
		{SETTINGS_KEY_FULL_PRESC, "Prescr", true, SETTING_DATATYPE_NONE, SETTING_LVOBJ_NONE},
		{SETTINGS_KEY_FULL_PRESC_CHANGE, "Prescr Apply", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SWITCH},
#endif

		/* Blower Settings */
		{SETTINGS_KEY_FULL_BLOWER, "Blower", true, SETTING_DATATYPE_NONE, SETTING_LVOBJ_NONE},
#if (SETTINGS_NEEDED)
		{SETTINGS_KEY_FULL_BLOWER_VOLTAGE, "Voltage", true, SETTING_DATATYPE_UINT32, SETTING_LVOBJ_SPINBOX},
		{SETTINGS_KEY_FULL_BLOWER_SPEED, "Speed", true, SETTING_DATATYPE_UINT32, SETTING_LVOBJ_SPINBOX},
		{SETTINGS_KEY_FULL_BLOWER_DUTY, "Duty", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SLIDER},
#endif
		{SETTINGS_KEY_FULL_BLOWER_PRESS_PA, "Pressure", true, SETTING_DATATYPE_INT, SETTING_LVOBJ_SPINBOX},
		{SETTINGS_KEY_FULL_BLOWER_STATE, "On/Off", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SWITCH},				// 13

#if (SETTINGS_NEEDED)
		/* Stepper Settings */
		{SETTINGS_KEY_FULL_STEPPER, "Stepper", true, SETTING_DATATYPE_NONE, SETTING_LVOBJ_NONE},
		{SETTINGS_KEY_FULL_STEPPER_RESET_POS, "Rst Pos", true, SETTING_DATATYPE_UINT16, SETTING_LVOBJ_SLIDER},
		{SETTINGS_KEY_FULL_STEPPER_STEP_SPEED_HZ, "Step Speed", true, SETTING_DATATYPE_UINT32, SETTING_LVOBJ_SLIDER},
		{SETTINGS_KEY_FULL_STEPPER_RESET_ROT_CNT, "Rot Cnt", true, SETTING_DATATYPE_UINT32, SETTING_LVOBJ_SPINBOX},
		{SETTINGS_KEY_FULL_STEPPER_RESET_DIR, "Direction", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SWITCH},
		{SETTINGS_KEY_FULL_STEPPER_STEP_MODE, "Step Mode", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_ROLLER},
		{SETTINGS_KEY_FULL_STEPPER_STEP_ANGLE, "Step Angle", true, SETTING_DATATYPE_UINT16, SETTING_LVOBJ_SLIDER},
#endif

		/* Personalization */
		{SETTINGS_KEY_FULL_PERSONALIZATION, "Personal", true, SETTING_DATATYPE_NONE, SETTING_LVOBJ_NONE},
		{SETTINGS_KEY_FULL_PERS_BRIGHT, "Bright", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SLIDER},
		{SETTINGS_KEY_FULL_PERS_SCREENON_TM, "Scr Off", true, SETTING_DATATYPE_UINT32, SETTING_LVOBJ_SLIDER},
		{SETTINGS_KEY_FULL_PERS_KPSOUND, "Key Sound", true, SETTING_DATATYPE_UINT8, SETTING_LVOBJ_SWITCH},					// 17

		/* Date time */
		{SETTINGS_KEY_FULL_DATETIME, "Datetime", true, SETTING_DATATYPE_NONE, SETTING_LVOBJ_NONE},
		{SETTINGS_KEY_FULL_DT_DATE, "Date", true, SETTING_DATATYPE_DATETIME, SETTING_LVOBJ_ROLLER},
		{SETTINGS_KEY_FULL_DT_TIME, "Time", true, SETTING_DATATYPE_DATETIME, SETTING_LVOBJ_ROLLER},		// 20
#endif

		{SETTINGS_KEY_FULL_LOD, "", 0, true, SETTING_DATATYPE_UINT8, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //0
		{SETTINGS_KEY_FULL_BST, "", 0, true, SETTING_DATATYPE_UINT8, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //1
		{SETTINGS_KEY_FULL_DEV_USB, "USB select", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_devUSB, NULL},        //2
		{SETTINGS_KEY_FULL_DEV, "Developer", 1, false, SETTING_DATATYPE_NONE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //3
		{SETTINGS_KEY_FULL_TS_EDT, "exhalation detection threshold", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_EDT, &g_mdata_CPAP, NULL},        //4
		{SETTINGS_KEY_FULL_TS_MNT, "ti min", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_minTI, &g_mdata_CPAP, NULL},        //5
		{SETTINGS_KEY_FULL_TS_MXT, "ti max", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_maxTI, &g_mdata_CPAP, NULL},        //6
		{SETTINGS_KEY_FULL_TS_FXT, "ti (fixed)", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_fixedTI, &g_mdata_CPAP, NULL},        //7
		{SETTINGS_KEY_FULL_TS_RIT, "rise time", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_riseTime, &g_mdata_CPAP, NULL},        //8
		{SETTINGS_KEY_FULL_TS_RR, "rr", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_RR, &g_mdata_CPAP, NULL},        //9
		{SETTINGS_KEY_FULL_TS_PRS, "Pressure Support", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_PSSupport, &g_mdata_CPAP, NULL},        //10
		{SETTINGS_KEY_FULL_TS_MNE, "minEPAP, minCPAP", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_minEPAPCPAP, &g_mdata_CPAP, NULL},        //11
		{SETTINGS_KEY_FULL_TS_FXE, "fixed epap, cpap", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_fixedEPAPCPAP, &g_mdata_CPAP, NULL},        //12
		{SETTINGS_KEY_FULL_TS_IPA, "ipap", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 3, g_modeParam_IPAP, &g_mdata_CPAP, NULL},        //13
		{SETTINGS_KEY_FULL_TS_MXI, "maxIPAP", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_maxIPAP, &g_mdata_CPAP, NULL},        //14
		{SETTINGS_KEY_FULL_TS_MXC, "max CPAP", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_maxCPAP, &g_mdata_CPAP, NULL},        //15
		{SETTINGS_KEY_FULL_TS_MNC, "min CPAP", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 1, g_modeParam_minCPAP, &g_mdata_CPAP, NULL},        //16
		{SETTINGS_KEY_FULL_TS_FIC, "CPAP", 2, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 2, g_modeParam_CPAP, &g_mdata_CPAP, NULL},        //17
		{SETTINGS_KEY_FULL_TS_MOD, "Mode", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_Mode, NULL},        //18
		{SETTINGS_KEY_FULL_TS, "Tech Settings", 1, false, SETTING_DATATYPE_NONE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //19
		{SETTINGS_KEY_FULL_DS_NET, "Network", 1, true, SETTING_DATATYPE_NONE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //20
		{SETTINGS_KEY_FULL_DS_NET_WI, "Wi-Fi", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_WiFi, NULL},        //21
		{SETTINGS_KEY_FULL_DS_NET_WIAP, "Hotspot", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_WiFiAP, settings_hotspot_extra_func},        //22
		{SETTINGS_KEY_FULL_DS_LAN, "language", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_lang, NULL},        //23
		{SETTINGS_KEY_FULL_DS_ERD, "Erase Data", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_EraseData, NULL},        //24
		{SETTINGS_KEY_FULL_DS_PAE, "pt access exh", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_ptAccExt, NULL},        //25
		{SETTINGS_KEY_FULL_DS_FRS, "Factory Reset", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_Freset, NULL},        //26
		{SETTINGS_KEY_FULL_DS_TIM, "Time", 1, true, SETTING_DATATYPE_TIME, GUI_OBJ_ROLLER, 0, NULL, g_mdata_Time, NULL},        //27
		{SETTINGS_KEY_FULL_DS_TIM_HR, "Hour", 0, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //28
		{SETTINGS_KEY_FULL_DS_TIM_MIN, "Min", 0, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //29
		{SETTINGS_KEY_FULL_DS_DAT, "Date", 1, true, SETTING_DATATYPE_DATE, GUI_OBJ_ROLLER, 0, NULL, g_mdata_Date, NULL},        //30
		{SETTINGS_KEY_FULL_DS_DAT_YR, "Year", 0, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //31
		{SETTINGS_KEY_FULL_DS_DAT_MON, "Month", 0, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //32
		{SETTINGS_KEY_FULL_DS_DAT_DAY, "Day", 0, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //33
		{SETTINGS_KEY_FULL_DS_SRN, "SN", 1, false, SETTING_DATATYPE_STRING, GUI_OBJ_LABEL, 0, NULL, NULL, NULL},        //34
		{SETTINGS_KEY_FULL_DS, "Device Settings", 1, false, SETTING_DATATYPE_NONE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //35
		{SETTINGS_KEY_FULL_CS_LAL, "Leak Alert", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_LeakAlert, NULL},        //36
		{SETTINGS_KEY_FULL_CS_AOF, "AutoOff", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_AutoOff, NULL},        //37
		{SETTINGS_KEY_FULL_CS_AON, "AutoOn", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_AutoOn, NULL},        //38
		{SETTINGS_KEY_FULL_CS_STM, "Settle Time", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_SettleTime, NULL},        //39
		{SETTINGS_KEY_FULL_CS_RTM, "Ramp Time", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_RampTime, NULL},        //40
		{SETTINGS_KEY_FULL_CS_HUM, "Humidity", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_Humidity, NULL},        //41
		{SETTINGS_KEY_FULL_CS_POU, "Place of use", 1, true, SETTING_DATATYPE_SETTING_VALUE, GUI_OBJ_ROLLER, 0, NULL, &g_mdata_PlaceOfUse, NULL},        //42
		{SETTINGS_KEY_FULL_CS, "Comfort Settings", 1, false, SETTING_DATATYPE_NONE, GUI_OBJ_NONE, 0, NULL, NULL, NULL},        //43
		{SETTINGS_KEY_FULL_NAM, "User", 1, false, SETTING_DATATYPE_STRING, GUI_OBJ_LABEL, 0, NULL, NULL, NULL},        //44
};



